### ISSUE TITLE
CSV generated from ANNOVAR may violate format rules in some cases

### ISSUE THREAD

**Issue by pdonorio** [WGLab/doc-ANNOVAR#1]
e.g. the last column contains commas:
"1/1:0,131:133:99:4445,358,0"
This also happens on random fields.

From [wikipedia](http://en.wikipedia.org/wiki/Comma-separated_values#Basic_rules_and_examples):
"*Fields with embedded commas or double-quote characters must be quoted.*"

The page containing informations about CSV is [here](https://github.com/WangGenomicsLab/doc-ANNOVAR/blob/master/docs/user-guide/startup.md)

**Comment by kaichop** [comment]
Can you provide some additional detail such as an example? From what I see above, the last column is indeed quoted, so it does not violate the rule that "Fields with embedded commas or double-quote characters must be quoted."

**Comment by pdonorio** [comment]
> From what I see above, the last column is indeed quoted

Sorry, in that case the quotes where added by me to report the piece of data.
There are no quotes in ANNOVAR csv output as far as i know, e.g. here is one whole line

```
chrM,410,410,A,T,intergenic,NONE,NONE,dist=NONE;dist=NONE,.,.,.,.,.,.,.,.,.,.,.,rs28412942,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,1,445.77,13,chrM,410,.,A,T,445.77,.,AC=2;AF=1.00;AN=2;DP=13;Dels=0.00;FS=0.000;HaplotypeScore=0.0000;MLEAC=2;MLEAF=1.00;MQ=60.00;MQ0=0;QD=34.29,GT:AD:DP:GQ:PL,1/1:0,13:13:39:474,39,0
```

This is my input file:
http://j.mp/myvcfexample

Command used to produce the file with release 2014nov12:

```
$ table_annovar.pl input.vcf -buildver hg19 human_db/ -outfile out.annotated -remove -protocol refGene,cytoBand,genomicSuperDups,esp6500si_all,1000g2014oct_all,1000g2014oct_afr,1000g2014oct_amr,1000g2014oct_eas,1000g2014oct_eur,1000g2014oct_sas,snp138NonFlagged,ljb23_all -operation g,r,r,f,f,f,f,f,f,f,f,f -nastring . -vcfinput -csvout
```

To describe a more generic problem, the number of fields in the header/first row,
should be equal to any row in the csv. 
In the example line above you will find 64 elements against the 48 columns of the header.
Here is the whole csv header line:
```
Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,AAChange.refGene,cytoBand,genomicSuperDups,esp6500si_all,1000g2014oct_all,1000g2014oct_afr,1000g2014oct_amr,1000g2014oct_eas,1000g2014oct_eur,1000g2014oct_sas,snp138NonFlagged,LJB23_SIFT_score,LJB23_SIFT_score_converted,LJB23_SIFT_pred,LJB23_Polyphen2_HDIV_score,LJB23_Polyphen2_HDIV_pred,LJB23_Polyphen2_HVAR_score,LJB23_Polyphen2_HVAR_pred,LJB23_LRT_score,LJB23_LRT_score_converted,LJB23_LRT_pred,LJB23_MutationTaster_score,LJB23_MutationTaster_score_converted,LJB23_MutationTaster_pred,LJB23_MutationAssessor_score,LJB23_MutationAssessor_score_converted,LJB23_MutationAssessor_pred,LJB23_FATHMM_score,LJB23_FATHMM_score_converted,LJB23_FATHMM_pred,LJB23_RadialSVM_score,LJB23_RadialSVM_score_converted,LJB23_RadialSVM_pred,LJB23_LR_score,LJB23_LR_pred,LJB23_GERP++,LJB23_PhyloP,LJB23_SiPhy,Otherinfo
```

If it may be of any help, this is a python snippet to check if every row of the file matches the length of the header:
https://gist.github.com/pdonorio/b55c43b23f9dcf7acc86

**Comment by kaichop** [comment]
Hi Paolo,
I guess you used an outdated version of table_annovar (even earlier than
2014nov12). The -vcfinput and -csvout are not allowed to be used in the
same command in recent versions.
The CSV file (when using a regular avinput file) indeed has comma
surrounding the fields.
Thanks.
-Kai

**Comment by pdonorio** [comment]
> The CSV file (when using a regular avinput file) indeed has comma
surrounding the fields.

Did you mean "quotation marks" instead of "comma" ?

**Comment by kaichop** [comment]
Yes I mean quotatation (").

**Comment by pdonorio** [comment]
Thanks, i will try to test on my laptop as soon as possible the latest version i just downloaded (2015Mar22) to confirm

**Comment by kaichop** [comment]
issue resolved and closed.
