### ISSUE TITLE
Please update prepare_annovar_user for COSMIC v.91-92

### ISSUE THREAD

**Issue by RKV82** [WGLab/doc-ANNOVAR#100]
Dear Prof. Wang!

I've tried to convert COSMIC tsv files to ANNOVAR, but encountered the same problem as in Issue #77

Could you update prepare_annovar_user.pl to handle the COSMIC v91 and upcoming v92

Thanks in advance.

**Comment by ArshiyaG** [comment]
Hey @RKV82 ,

Unzip the cosmic tsv file and try running the command again. It worked for me

**Comment by RKV82** [comment]
> Unzip the cosmic tsv file and try running the command again. It worked for me

Thanks, but for GenomeScreenMutant it still not work. Solved by `cut -f 1-16,18-39`

**Comment by kaichop** [comment]
@RKV82 Thank you, if I understand correctly, the previous criteria **`if ($field[16] eq 'Mutation ID' or $field[16] eq 'GENOMIC_MUTATION_ID'`**) no longer works in v91 and v92, because they added a field right before the 17th column (which is $field[16])? If this is the case, I can add a new statement in the code and fix the issue so other users do not need to use the "cut" command. Thank you.

**Comment by RKV82** [comment]
> @RKV82 Thank you, if I understand correctly, the previous criteria **`if ($field[16] eq 'Mutation ID' or $field[16] eq 'GENOMIC_MUTATION_ID'`**) no longer works in v91 and v92, because they added a field right before the 17th column (which is $field[16])?

@kaichop Yes, the field 16 now is "Genome-wide screen". The field 17 in COSMIC Mutation Data (Genome Screens) is "MUTATION_ID", but for COSMIC Complete Mutation Data (Targeted Screens) and Mutations in Census Genes it named "GENOMIC_MUTATION_ID" 
On the attached image the top string is from COSMIC Mutation Data (Genome Screens) and the bottom one is from COSMIC Complete Mutation Data (Targeted Screens)
![2020-10-04_10-28-03](https://user-images.githubusercontent.com/68806567/95009652-5cc9f880-062c-11eb-9ec2-43357898b076.png)
Glad to help in your great work!

**Comment by kaichop** [comment]
The issue was fixed, and the updated script works on all four types of files (CosmicMutantExport.tsv, CosmicCompleteTargetedScreensMutantExport.tsv, CosmicGenomeScreensMutantExport.tsv, CosmicNCV.tsv).

**Comment by abhijitswain62** [comment]
@kaichop prepare_annovar_user.pl -dbtype cosmic Cosmic_GenomeScreensMutant_v101_GRCh37.tsv -vcf Cosmic_GenomeScreensMutant_v101_GRCh37.vcf > hg19_cosmic101.txt 
NOTICE: Finished reading 13601142 mutation ID from the VCF file Cosmic_GenomeScreensMutant_v101_GRCh37.vcf
Error: COSMIC MutantExport format error: column 17 or 18 or 12 should be 'Mutation ID' or 'GENOMIC_MUTATAION_ID' or 'ID_NCV'
not working for v101
