### ISSUE TITLE
Invalid record found in refgene file

### ISSUE THREAD

**Issue by ga23981** [WGLab/doc-ANNOVAR#102]
I am trying annotate my vcf file using ANNOVAR, however, when I perform the below step I get an error:

/annovar/2017Jul16-foss-2016b-Perl-5.24.1/retrieve_seq_from_fasta.pl --format refGene --seqfile Pvulgaris_442_v2.0.softmasked.fa Pvulgaris_442_v2.1_refGene.txt --out Pvulgaris_442_v2.1_refGeneMrna.fa

NOTICE: Reading region file Pvulgaris_442_v2.1_refGene.txt ... Error: invalid record found in 'refGene' file Pvulgaris_442_v2.1_refGene.txt (15 or 16 fields expected): <Phvul.001G000400.1.v2.1        Chr01   -       705     6715    951     6655    6       705,3314,3855,4306,6259,6520, 1266,3407,3988,4453,6426,6715,>

I obtained my Pvulgaris_442_v2.1_refGene.txt file using the following commands:

gffread -E Pvulgaris_442_v2.1.gene.gff3 -T -o Pvulgaris_442_v2.1.gene.gtf

singularity exec /usr/local/singularity-images/gtftogenepred-377.3.sif gtfToGenePred Pvulgaris_442_v2.1.gene.gtf Pvulgaris_442_v2.1_refGene.txt

Could you please suggest me how do I get it working.

Please let me know if you would need my input files to look into?

**Comment by kaichop** [comment]
The basic format is below (the first "bin" can be optional). From what you
describe below, you can simply add five extra columns yourself to the file,
and then run it again (these columns are not useful in annovar except name2
which is the name of the gene).


fieldexampleSQL typeinfodescription
bin 585 smallint(5) unsigned range
<https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=874970887_ZyAuqJf7XBEkStD1AdIlwMxG26Fm&hgta_database=hg19&hgta_histoTable=ncbiRefSeq&hgta_doValueRange=bin>
Indexing
field to speed chromosome range queries.
name NR_046018.2 varchar(255) values
<https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=874970887_ZyAuqJf7XBEkStD1AdIlwMxG26Fm&hgta_database=hg19&hgta_histoTable=ncbiRefSeq&hgta_doValueHistogram=name>
Name
of gene (usually transcript_id from GTF)
chrom chr1 varchar(255) values
<https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=874970887_ZyAuqJf7XBEkStD1AdIlwMxG26Fm&hgta_database=hg19&hgta_histoTable=ncbiRefSeq&hgta_doValueHistogram=chrom>
Reference
sequence chromosome or scaffold
strand + char(1) values
<https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=874970887_ZyAuqJf7XBEkStD1AdIlwMxG26Fm&hgta_database=hg19&hgta_histoTable=ncbiRefSeq&hgta_doValueHistogram=strand>
+
or - for strand
txStart 11873 int(10) unsigned range
<https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=874970887_ZyAuqJf7XBEkStD1AdIlwMxG26Fm&hgta_database=hg19&hgta_histoTable=ncbiRefSeq&hgta_doValueRange=txStart>
Transcription
start position (or end position for minus strand item)
txEnd 14409 int(10) unsigned range
<https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=874970887_ZyAuqJf7XBEkStD1AdIlwMxG26Fm&hgta_database=hg19&hgta_histoTable=ncbiRefSeq&hgta_doValueRange=txEnd>
Transcription
end position (or start position for minus strand item)
cdsStart 14409 int(10) unsigned range
<https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=874970887_ZyAuqJf7XBEkStD1AdIlwMxG26Fm&hgta_database=hg19&hgta_histoTable=ncbiRefSeq&hgta_doValueRange=cdsStart>
Coding
region start (or end position for minus strand item)
cdsEnd 14409 int(10) unsigned range
<https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=874970887_ZyAuqJf7XBEkStD1AdIlwMxG26Fm&hgta_database=hg19&hgta_histoTable=ncbiRefSeq&hgta_doValueRange=cdsEnd>
Coding
region end (or start position for minus strand item)
exonCount 3 int(10) unsigned range
<https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=874970887_ZyAuqJf7XBEkStD1AdIlwMxG26Fm&hgta_database=hg19&hgta_histoTable=ncbiRefSeq&hgta_doValueRange=exonCount>
Number
of exons
exonStarts 11873,12612,13220, longblob   Exon start positions (or end
positions for minus strand item)
exonEnds 12227,12721,14409, longblob   Exon end positions (or start
positions for minus strand item)
score 0 int(11) range
<https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=874970887_ZyAuqJf7XBEkStD1AdIlwMxG26Fm&hgta_database=hg19&hgta_histoTable=ncbiRefSeq&hgta_doValueRange=score>
score
name2 DDX11L1 varchar(255) values
<https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=874970887_ZyAuqJf7XBEkStD1AdIlwMxG26Fm&hgta_database=hg19&hgta_histoTable=ncbiRefSeq&hgta_doValueHistogram=name2>
Alternate
name (e.g. gene_id from GTF)
cdsStartStat none enum('none', 'unk', 'incmpl', 'cmpl') values
<https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=874970887_ZyAuqJf7XBEkStD1AdIlwMxG26Fm&hgta_database=hg19&hgta_histoTable=ncbiRefSeq&hgta_doValueHistogram=cdsStartStat>
Status
of CDS start annotation (none, unknown, incomplete, or complete)
cdsEndStat none enum('none', 'unk', 'incmpl', 'cmpl') values
<https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=874970887_ZyAuqJf7XBEkStD1AdIlwMxG26Fm&hgta_database=hg19&hgta_histoTable=ncbiRefSeq&hgta_doValueHistogram=cdsEndStat>
Status
of CDS end annotation (none, unknown, incomplete, or complete)
exonFrames -1,-1,-1, longblob   Exon frame {0,1,2}, or -1 if no frame for
exon

**Comment by ga23981** [comment]
Thank you, it worked!
