### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by lassefolkersen** [WGLab/doc-ANNOVAR#107]
Minor typo `suffplied` in [startup.md](https://github.com/WGLab/doc-ANNOVAR/blob/master/docs/user-guide/startup.md) and a broken link at `he result file can be downloaded from here` (it points to [this](https://doc-openbio.readthedocs.io/projects/annovar/en/latest/user-guide/ex1_full.hg19_multianno.csv)). I think maybe the broken link instead should be http://www.openbioinformatics.org/annovar/download/ex1.hg19_multianno.csv - so at the www.openbioinformatics.org site.

Thanks for a great program!

**Comment by kaichop** [comment]
Thank you, fixed.
