### ISSUE TITLE
prediction of novel variants 

### ISSUE THREAD

**Issue by bushrabibi** [WGLab/doc-ANNOVAR#108]
Hi everyone, 
What does "." dot represents in dbSNP column of Annovar output, does it verifies novel variants? How can we identify novel variants from annovar output. Your suggestion will be really appreaciated. Thanks,

**Comment by kaichop** [comment]
It means not in dbSNP.

**Comment by kaichop** [comment]
you can use a few filter databases including gnomad (exome and genome) to
find variants that are not reported before.

**Comment by bushrabibi** [comment]
Thanks for your response Kaichop!

**Comment by bushrabibi** [comment]
Hi kaichop! 
I observed differences in choromosomal positions given in first column "VARIATION ID" e.g.,

**chr10:89622240:C/CGGC:1** and third column "Position" e.g.,
89622241.
Here you can see the difference of 89622240 and 89622241

Should not these locations be the same? Which location shoud be followed as SNP position?

Looking forward to your response.

Kind Regards

**Comment by bushrabibi** [comment]
Hi kaichop! 
I observed differences in **choromosomal positions** given in first column **"VARIATION ID"** e.g.,

**chr10:89622240:C/CGGC:1** 

and third column "**Position**" e.g.,

**89622241**.

Here you can see the difference of **89622240** and **89622241**

Should not these locations be the same? Which location should be followed as SNP position?

Looking forward to your response.

Kind Regards
