### ISSUE TITLE
Annnotated VCF missing new INFO headers

### ISSUE THREAD

**Issue by sxv** [WGLab/doc-ANNOVAR#11]
When annotating with table_annovar.pl, my output VCF file contains several new entries in the INFO column, as expected. However these new INFO values are not added to the meta-information header lines at the top of the VCF file.

The VCF specification states "It is strongly encouraged that information lines describing the INFO, FILTER, and FORMAT entries used in the body of the VCF file be included in the meta-information section."

Several downstream VCF tools, including bcftools, require these INFO headers to be present in order to parse VCFs. So while they are technically optional, it seems like best practice to include them in the VCF output.

Thoughts?

**Comment by kaichop** [comment]
They should be included.
If you can provide the command line and the example header that would be
helpful.

**Comment by sxv** [comment]
Is it possible this was fixed in a recent release? I am unable to reproduce this result with the new version of ANNOVAR, but my old annotated VCFs lack the INFO headers..

**Comment by kaichop** [comment]
Yes it is fixed in a previous release (not so recent though).

**Comment by sxv** [comment]
Great, thanks for your lightning speed response!
