### ISSUE TITLE
bug in wannovar

### ISSUE THREAD

**Issue by kaichop** [WGLab/doc-ANNOVAR#13]
using the link for the anemia example (http://wannovar.usc.edu/done/1/THtp3lWHEh893pWw/index.html)

Click exome summary results/view. Results consist of 173 pages, 100 variants each one.

Filtering by exonic function / stopgain SNV works, reducing the list of variants, but according to the info in the ExonicFunc column, it includes several kinds of SNVs, not only stopgain variants

**Comment by cemalley** [comment]
Link broken as of Jul 29. Is this fixed?

**Comment by kaichop** [comment]
this is fixed.
