### ISSUE TITLE
Annovar & Bioconda

### ISSUE THREAD

**Issue by matthdsm** [WGLab/doc-ANNOVAR#14]
Dear Mr. Wang,

Would it be possible to get to some kind of licensing agreement to make it possible to make ANNOVAR available as a package in de conda package manager.

Conda is being widely used throughout the scientific community, and adding your excellent software to this system would be of great advantage to everyone. It would also greatly improve the visibility and ease of use of your software.

Thank you for your time
Matthias De Smet and all of the bioconda community

PS: check us out at https://bioconda.github.io

**Comment by kaichop** [comment]
I cannot include it per university requirement.
