### ISSUE TITLE
Suggestion to add the number of mutated exon/the number of total exons of a gene.

### ISSUE THREAD

**Issue by lincj1994** [WGLab/doc-ANNOVAR#151]
Hi. I dont know if it is possible fo ANNOVAR to add the number of mutated exon/the number of total exons of a gene in the output to predict NMD escape.
Lin.

**Comment by kaichop** [comment]
The output includes the exon number for each transcript. You need to
calculate the number of total exon for each transcript yourself (from
hg19_refGene.txt file), and then check whether that exon is the last exon
or not.
