### ISSUE TITLE
Creating an avinput from avsnp file error

### ISSUE THREAD

**Issue by rbutleriii** [WGLab/doc-ANNOVAR#16]
I am having an issue with convert2annovar.pl from an rsID list. Using the following:

convert2annovar.pl -format rsid rslist.txt -dbsnpfile ${annovar}humandb/hg19_avsnp147.txt > rslist.avinput

I get:
NOTICE: Scanning dbSNP file /opt/annovar/humandb/hg19_avsnp147.txt...
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 1.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 1.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 1.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 1.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 2.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 2.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 2.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 2.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 3.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 3.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 3.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 3.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 4.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 4.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 4.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 4.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 5.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 5.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 5.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 5.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 6.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 6.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 6.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 6.
Use of uninitialized value $class in string eq at /opt/annovar/convert2annovar.pl line 1022, <DBSNP> line 7.

And so forth for all lines (I stopped checking after more than a million lines). Input file looks like:
rs150829393
rs112039851
rs1800562
rs200401432
rs118161496
rs1799945

And does the same with or without the rs prefix. Is there a different dbSNP file to use?

**Comment by kaichop** [comment]
avsnp is not supported. You could simply "grep -w -f rslist.txt
hg19_avsnp147.txt" to generate the desired file.

**Comment by rbutleriii** [comment]
Worked, perhaps in the next version of convert2annovar.pl it will simply grep, as snp138 is from 2014.

**Comment by rbutleriii** [comment]
FYI for long lists I used a perl block to take an rsID list mapped to hash keys (%rsIDbatch) and make the avinput file:

open(IN7, "$anno_avsnp_file");
open(OUT4, ">rslist.avinput");
while (my $line = <IN7>){
	chomp $line;
	$line =~ /rs(\d+)$/;
		if (exists $rsIDbatch{$1}){
			print OUT4 "$line\n";
		} else { next; }
}
close IN7;
close OUT4;

Massively shortens execution time. Could be useful for others, or for generating inputs to InterVar.

**Comment by kaichop** [comment]
Thank you for the comments. This function will be added in the next version
of ANNOVAR.
