### ISSUE TITLE
NM_004260:exon14:c.2296+1C>-;NM_004260:exon15:c.2297-1C>-

### ISSUE THREAD

**Issue by asmlgkj** [WGLab/doc-ANNOVAR#163]
is this the same meaning of variant
thanks a lot
chr8 145738768 145738768 G - splicing RECQL4 NM_004260:exon14:c.2296+1C>-;NM_004260:exon15:c.2297-1C>-

**Comment by kaichop** [comment]
There is a 1bp intron between exon 14 and exon 15 (possibly a problem with
reference genome assembly itself). Therefore, this variant is annotated as
splice variant for both exons.
