### ISSUE TITLE
LoFTool in table_annovar.pl

### ISSUE THREAD

**Issue by rbutleriii** [WGLab/doc-ANNOVAR#17]
I am not sure I have the correctly formatted loftool database. I downloaded the file from the readthedocs website (LoFtool_scores.txt) and renamed it to /opt/annovar/humandb/hg19_loftool.txt but when I run table_annovar.pl with this command:

table_annovar.pl rslist.avinput ${annovar}humandb/ -buildver hg19 -out rslist -remove -protocol dbnsfp33a,exac03,gnomad_exome,clinvar_20170130,loftool -operation f,f,f,f,g -nastring "-"

I get correct outputs for every other operation but loftool:
NOTICE: Processing operation=g protocol=loftool

NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg19 -dbtype loftool -outfile rslist.loftool -exonsort rslist.avinput /opt/annovar/humandb/>
NOTICE: Output files were written to rslist.loftool.variant_function, rslist.loftool.exonic_variant_function
NOTICE: Reading gene annotation from /opt/annovar/humandb/hg19_loftool.txt ... Error: invalid record in /opt/annovar/humandb/hg19_loftool.txt (>=11 fields expected in loftool gene definition file): <Gene	LoFtool_percentile>
Error running system command: <annotate_variation.pl -geneanno -buildver hg19 -dbtype loftool -outfile rslist.loftool -exonsort rslist.avinput /opt/annovar/humandb/>

Do I need to process the Loftool file prior to running annovar (it only has two columns, << 11 it is looking for)?

**Comment by kaichop** [comment]
operation is f

**Comment by rbutleriii** [comment]
Running the operation as f I get this message:

NOTICE: Scanning filter database /opt/annovar/humandb/hg19_loftool.txt...Error: invalid database entry (generic ANNOVAR database should contain at least 4 tab-delimited fields per line): <Gene	LoFtool_percentile>
Error running system command: <annotate_variation.pl -filter -dbtype loftool -buildver hg19 -outfile rslist rslist.avinput /opt/annovar/humandb/>

Head of file from http://www.openbioinformatics.org/annovar/download/LoFtool_scores.txt.gz :
Gene	LoFtool_percentile
NIPBL	6.89E-05
SCN1A	1.38E-04
NOTCH1	2.07E-04
TSC2	2.76E-04
PTCH1	3.44E-04
SCN5A	4.13E-04
EP300	4.82E-04
CACNA1C	5.51E-04

**Comment by kaichop** [comment]
Okay I see. loftool is a gene score, similar to pLI or RVIS. It cannot be
used in the current version of ANNOVAR. It is provided for users to
post-filter their results and identify causal genes.
