### ISSUE TITLE
Not able to download hg19_gerp++elem.txt.idx.gz

### ISSUE THREAD

**Issue by agarwalsurbhi** [WGLab/doc-ANNOVAR#176]
Dear Prof. Wang,

I am trying to download gerp++elem database for hg19 using command 
**<perl annotate_variation.pl -buildver hg19 -downdb -webfrom annovar gerp++elem humandb/>**

which is producing the following error while downloading hg19_gerp++elem.txt.idx.gz file

NOTICE: Web-based checking to see whether ANNOVAR new version is available ... Done
NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg19_gerp++elem.txt.gz ... OK
**NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg19_gerp++elem.txt.idx.gz ... **Failed****
NOTICE: Uncompressing downloaded files
NOTICE: Finished downloading annotation files for hg19 build version, with files saved at the 'humandb' directory
**WARNING: Some files cannot be downloaded, including http://www.openbioinformatics.org/annovar/download/hg19_gerp++elem.txt.idx.gz**

Is hg19_gerp++elem.txt.idx.gz missing at the source? Is there another way possible to use this database? 
Also, the database was last updated in 2014. Are there any possibilities of new update?

Thanks! I will appreciate your help.

Surbhi

**Comment by kaichop** [comment]
This is fine. The file is a region annotation file so idx is not required.
The region is taken from published paper. The hg38 version is not available
as the original publication only provides hg19/mm9. There is no update from
the authors as far as I know.

**Comment by agarwalsurbhi** [comment]
Dear Prof. Wang, 

Thank you for your response.
I tried annotation without that file and ANNOVAR ran successfully. 

I really appreciate your help.
Thanks

Surbhi
