### ISSUE TITLE
Converting annotated VCF to txt file

### ISSUE THREAD

**Issue by kvn95ss** [WGLab/doc-ANNOVAR#181]
Hello,

I wanted to know if there is any native way to convert an annovar annotated VCF to txt file.

**Comment by kaichop** [comment]
VCF file is already a text file. If you mean to get the annotation out,
then they are all in a field, and you need to write a script to extract
each annotation from each line. I remember there are some R modules that
can extract a specific annotation from annovar-annotated VCF file but I
never used them.

**Comment by kvn95ss** [comment]
Thanks for the information!
