### ISSUE TITLE
parse clinvar xml by annovar

### ISSUE THREAD

**Issue by asmlgkj** [WGLab/doc-ANNOVAR#189]
thanks a lot for this excellent tool
due to the frequent update of clinvar, and vcf contains too little few info, for example, variant id(not allele id) and pmid, though there was separately files contains such, so does annovar can parse clinvar xlm?

**Comment by kaichop** [comment]
It does not process XLM file. But there was a recent update
clinvar_20220320 that you can use.
I am not sure what is a variant ID, in general the best way to identify a
variant is the chr and position, not an ID. Most variants in clinvar has no
PMID, since they are direct submissions.

**Comment by asmlgkj** [comment]
![image](https://user-images.githubusercontent.com/50854682/165883533-d07b3c81-8ffc-422a-84a4-a36f41cd5326.png)
it was here variant ID, I have found a file about that, thanks a lot
