### ISSUE TITLE
table_annovar.pl does not respect -nastring option when processing 1000G datasets

### ISSUE THREAD

**Issue by mys721tx** [WGLab/doc-ANNOVAR#20]
When annotating 1000G dataset, the NaN string will be `.` regardless of `-nastring` option.

Step to reproduce:
1. `./table_annovar.pl example/ex1.avinput humandb/ -buildver hg19 -out myanno -remove -protocol popfreq_all_20150413 -operation f -nastring NaN -csvout -polish`

**Comment by kaichop** [comment]
the "." may be already in the database itself (this happens for some
multiple column databases where some columns have "."), so it is not
treated as 'not available' here. Only entries that are not found in the
database is considered in -nastring.

**Comment by mys721tx** [comment]
`table_annovar.pl` could be modified to parse the result of `annotate_variation.pl` and replace the NA string appropriately. I will think about that and submit a patch once I get it working.
