### ISSUE TITLE
Annotation of exon-intron junction variant

### ISSUE THREAD

**Issue by Bin-Guan** [WGLab/doc-ANNOVAR#207]
We used annovar/2020-06-08 for the hg19 variant 6-64574078-CC-TA, which resulted in EYS; exonic,splicing; nonsynonymous SNV; EYS:NM_001142800.2:exon36:c.7228G>T:p.A2410S. Because the variant is at the exon-intron junction, so a proper annotation could be "splicing" instead of "nonsynonymous SNV" & c.7228_7228+1delinsTA. Possible to change the behavior here? 

Thanks.

**Comment by kaichop** [comment]
The annotation seems to be exonic,splicing already, which means it disrupts
exon region but also splice site. ANNOVAR does not give HGVS notation to
splice variants that disrupt multiple nucleotide though, so it shows as
p.A2410S. I hope this helps.

**Comment by Bin-Guan** [comment]
Thanks!
