### ISSUE TITLE
Gene.refGene shows NM_ number of the upstream gene?

### ISSUE THREAD

**Issue by Yiran-Guo** [WGLab/doc-ANNOVAR#21]
It seems Annovar uses the previous Gene.refGene to annotate a variant of the next gene. For example, NM_152486 is for SAMD11 but in the third line it is still in the Gene.refGene field where NM_015658 should be used (the gene is NOC2L now).

[http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&highlight=hg19.chr1:881627-881627&position=chr1:881577-881677](url)

1       877831  .       T       C       58.74   PASS    DP=3;MQ=60.00;FractionInformativeReads=1.000;ANNOVAR_DATE=2016-02-01;Func.refGene=exonic;**Gene.refGene=NM_152486**;GeneDetail.refGene=.;ExonicFunc.refGene=nonsynonymous_SNV;**AAChange.refGene=SAMD11:NM_152486:exo
n10:c.1027T>C:p.W343R**;cytoBand=1p36.33;genomicSuperDups=.;esp6500siv2_all=.;1000g2015aug_all=1;SIFT_score=1;SIFT_pred=T;Polyphen2_HDIV_score=0.0;Polyphen2_HDIV_pred=B;Polyphen2_HVAR_score=0.0;Polyphen2_HVAR_pred=B;LRT_score=0.003;LRT_pred=N;MutationTaster_score=1
.000;MutationTaster_pred=P;MutationAssessor_score=-2.085;MutationAssessor_pred=N;FATHMM_score=.;FATHMM_pred=.;RadialSVM_score=-0.980;RadialSVM_pred=T;LR_score=0.000;LR_pred=T;VEST3_score=0.421;CADD_raw=-1.112;CADD_phred=0.132;GERP++_RS=2.51;phyloP46way_placental=
0.624;phyloP100way_vertebrate=1.209;SiPhy_29way_logOdds=7.519;ExAC_ALL=0.9999;ExAC_AFR=1;ExAC_AMR=1;ExAC_EAS=1;ExAC_FIN=1;ExAC_NFE=1;ExAC_OTH=1;ExAC_SAS=0.9999;avsnp147=rs6672356;CLINSIG=.;CLNDBN=.;CLNACC=.;CLNDSDB=.;CLNDSDBID=.;gnomAD_genome_ALL=0.9998;gnomAD_ge
nome_AFR=0.9994;gnomAD_genome_AMR=1;gnomAD_genome_ASJ=1;gnomAD_genome_EAS=1;gnomAD_genome_FIN=1;gnomAD_genome_NFE=0.9999;gnomAD_genome_OTH=1;gnomAD_exome_ALL=0.9999;gnomAD_exome_AFR=0.9994;gnomAD_exome_AMR=0.9999;gnomAD_exome_ASJ=1;gnomAD_exome_EAS=1;gnomAD_exome
_FIN=1;gnomAD_exome_NFE=0.9999;gnomAD_exome_OTH=1;gnomAD_exome_SAS=0.9997;ALLELE_END;ANN=C|missense_variant|MODERATE|SAMD11|SAMD11|transcript|NM_152486.2|protein_coding|10/14|c.1027T>C|p.Trp343Arg|1107/2554|1027/2046|343/681||,C|downstream_gene_variant|MODIFIER|N
OC2L|NOC2L|transcript|NM_015658.3|protein_coding||c.*2243A>G|||||1752|;CSQ=C|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000420190|protein_coding|||||||||||1|3160|1|HGNC|28706||||||,C|downstream_gene_variant|MODIFIER|NOC2L|ENSG0000018
8976|Transcript|ENST00000496938|processed_transcript|||||||||||1|2868|-1|HGNC|24517||||||0.887,C|missense_variant|MODERATE|SAMD11|ENSG00000187634|Transcript|ENST00000342066|protein_coding|10/14||ENST00000342066.3:c.1027T>C|ENSP00000342313.3:p.Trp343Arg|1110|1027|
343|W/R|Tgg/Cgg||1||1|HGNC|28706|YES||CCDS2.2|NM_152486.2||,C|downstream_gene_variant|MODIFIER|NOC2L|ENSG00000188976|Transcript|ENST00000327044|protein_coding|||||||||||1|1753|-1|HGNC|24517|YES||CCDS3.1|NM_015658.3||0.887,C|non_coding_transcript_exon_variant&non_
coding_transcript_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000464948|retained_intron|1/2||ENST00000464948.1:n.286T>C||286||||||1||1|HGNC|28706||||||,C|non_coding_transcript_exon_variant&non_coding_transcript_variant|MODIFIER|SAMD11|ENSG00000187634
|Transcript|ENST00000466827|retained_intron|2/2||ENST00000466827.1:n.191T>C||191||||||1||1|HGNC|28706||||||,C|non_coding_transcript_exon_variant&non_coding_transcript_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000474461|retained_intron|3/4||ENST0000
0474461.1:n.389T>C||389||||||1||1|HGNC|28706||||||,C|missense_variant|MODERATE|SAMD11|ENSG00000187634|Transcript|ENST00000455979|protein_coding|4/7||ENST00000455979.1:c.507T>C|ENSP00000412228.1:p.Trp170Arg|507|508|170|W/R|Tgg/Cgg||1||1|HGNC|28706||||||,C|downstre
am_gene_variant|MODIFIER|NOC2L|ENSG00000188976|Transcript|ENST00000483767|retained_intron|||||||||||1|1753|-1|HGNC|24517||||||0.887,C|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000478729|processed_transcript|||||||||||1|278|1|HGNC|28
706||||||,C|downstream_gene_variant|MODIFIER|NOC2L|ENSG00000188976|Transcript|ENST00000477976|retained_intron|||||||||||1|1754|-1|HGNC|24517||||||0.887,C|missense_variant|MODERATE|SAMD11|ENSG00000187634|Transcript|ENST00000341065|protein_coding|8/12||ENST00000341
065.4:c.750T>C|ENSP00000349216.4:p.Trp251Arg|750|751|251|W/R|Tgg/Cgg||1||1|HGNC|28706||||||   GT:AD:DP:GQ:PL:SB       1/1:0,3,0:3:9:91,9,0,91,9,91:0,0,2,1
1       880238  .       A       G       1053.77 PASS    DP=52;MQ=60.00;MQRankSum=0.839;ReadPosRankSum=1.379;FractionInformativeReads=0.981;ANNOVAR_DATE=2016-02-01;Func.refGene=intronic\x3bdownstream;**Gene.refGene=NM_152486**;GeneDetail.refGene=.;ExonicFunc.refGene=.
;**AAChange.refGene=.**;cytoBand=1p36.33;genomicSuperDups=.;esp6500siv2_all=.;1000g2015aug_all=0.920927;SIFT_score=.;SIFT_pred=.;Polyphen2_HDIV_score=.;Polyphen2_HDIV_pred=.;Polyphen2_HVAR_score=.;Polyphen2_HVAR_pred=.;LRT_score=.;LRT_pred=.;MutationTaster_score=.;Mu
tationTaster_pred=.;MutationAssessor_score=.;MutationAssessor_pred=.;FATHMM_score=.;FATHMM_pred=.;RadialSVM_score=.;RadialSVM_pred=.;LR_score=.;LR_pred=.;VEST3_score=.;CADD_raw=.;CADD_phred=.;GERP++_RS=.;phyloP46way_placental=.;phyloP100way_vertebrate=.;SiPhy_29w
ay_logOdds=.;ExAC_ALL=.;ExAC_AFR=.;ExAC_AMR=.;ExAC_EAS=.;ExAC_FIN=.;ExAC_NFE=.;ExAC_OTH=.;ExAC_SAS=.;avsnp147=rs3748592;CLINSIG=.;CLNDBN=.;CLNACC=.;CLNDSDB=.;CLNDSDBID=.;gnomAD_genome_ALL=0.9351;gnomAD_genome_AFR=0.9087;gnomAD_genome_AMR=0.9487;gnomAD_genome_ASJ=
0.9238;gnomAD_genome_EAS=0.9066;gnomAD_genome_FIN=0.9614;gnomAD_genome_NFE=0.9460;gnomAD_genome_OTH=0.9490;gnomAD_exome_ALL=.;gnomAD_exome_AFR=.;gnomAD_exome_AMR=.;gnomAD_exome_ASJ=.;gnomAD_exome_EAS=.;gnomAD_exome_FIN=.;gnomAD_exome_NFE=.;gnomAD_exome_OTH=.;gnom
AD_exome_SAS=.;ALLELE_END;ANN=G|downstream_gene_variant|MODIFIER|SAMD11|SAMD11|transcript|NM_152486.2|protein_coding||c.*705A>G|||||277|,G|intron_variant|MODIFIER|NOC2L|NOC2L|transcript|NM_015658.3|protein_coding|18/18|c.2144-58T>C||||||;CSQ=G|downstream_gene_var
iant|MODIFIER|NOC2L|ENSG00000188976|Transcript|ENST00000496938|processed_transcript|||||||||||1|461|-1|HGNC|24517||||||0.887,G|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000342066|protein_coding|||||||||||1|283|1|HGNC|28706|YES||CCDS
2.2|NM_152486.2||,G|intron_variant|MODIFIER|NOC2L|ENSG00000188976|Transcript|ENST00000327044|protein_coding||18/18|ENST00000327044.6:c.2144-58T>C||||||||1||-1|HGNC|24517|YES||CCDS3.1|NM_015658.3||0.887,G|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Tra
nscript|ENST00000464948|retained_intron|||||||||||1|1966|1|HGNC|28706||||||,G|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000466827|retained_intron|||||||||||1|2056|1|HGNC|28706||||||,G|downstream_gene_variant|MODIFIER|SAMD11|ENSG0000
0187634|Transcript|ENST00000474461|retained_intron|||||||||||1|1864|1|HGNC|28706||||||,G|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000455979|protein_coding|||||||||||1|599|1|HGNC|28706||||||,G|intron_variant&non_coding_transcript_va
riant|MODIFIER|NOC2L|ENSG00000188976|Transcript|ENST00000483767|retained_intron||4/4|ENST00000483767.1:n.1015-58T>C||||||||1||-1|HGNC|24517||||||0.887,G|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000478729|processed_transcript|||||||
||||1|2685|1|HGNC|28706||||||,G|intron_variant&non_coding_transcript_variant|MODIFIER|NOC2L|ENSG00000188976|Transcript|ENST00000477976|retained_intron||16/16|ENST00000477976.1:n.3606-58T>C||||||||1||-1|HGNC|24517||||||0.887,G|downstream_gene_variant|MODIFIER|SAMD
11|ENSG00000187634|Transcript|ENST00000341065|protein_coding|||||||||||1|283|1|HGNC|28706||||||     GT:AD:DP:GQ:PL:SB       0/1:20,31,0:51:99:1082,0,546,1781,639,1781:8,12,14,17
1       881627  .       G       A       332.77  PASS    DP=25;MQ=60.00;MQRankSum=-0.739;ReadPosRankSum=-0.192;FractionInformativeReads=1.000;ANNOVAR_DATE=2016-02-01;Func.refGene=exonic\x3bdownstream;**Gene.refGene=NM_152486**;GeneDetail.refGene=.;ExonicFunc.refGene=s
ynonymous_SNV;**AAChange.refGene=NOC2L:NM_015658:exon16:c.1843C>T:p.L615L**;cytoBand=1p36.33;genomicSuperDups=.;esp6500siv2_all=0.4748;1000g2015aug_all=0.441893;SIFT_score=.;SIFT_pred=.;Polyphen2_HDIV_score=.;Polyphen2_HDIV_pred=.;Polyphen2_HVAR_score=.;Polyphen2_HVA
R_pred=.;LRT_score=.;LRT_pred=.;MutationTaster_score=.;MutationTaster_pred=.;MutationAssessor_score=.;MutationAssessor_pred=.;FATHMM_score=.;FATHMM_pred=.;RadialSVM_score=.;RadialSVM_pred=.;LR_score=.;LR_pred=.;VEST3_score=.;CADD_raw=.;CADD_phred=.;GERP++_RS=.;ph
yloP46way_placental=.;phyloP100way_vertebrate=.;SiPhy_29way_logOdds=.;ExAC_ALL=0.5653;ExAC_AFR=0.1397;ExAC_AMR=0.4840;ExAC_EAS=0.6560;ExAC_FIN=0.6221;ExAC_NFE=0.6283;ExAC_OTH=0.5737;ExAC_SAS=0.5648;avsnp147=rs2272757;CLINSIG=.;CLNDBN=.;CLNACC=.;CLNDSDB=.;CLNDSDBI
D=.;gnomAD_genome_ALL=0.4889;gnomAD_genome_AFR=0.1429;gnomAD_genome_AMR=0.4844;gnomAD_genome_ASJ=0.5265;gnomAD_genome_EAS=0.6751;gnomAD_genome_FIN=0.6175;gnomAD_genome_NFE=0.6336;gnomAD_genome_OTH=0.5855;gnomAD_exome_ALL=0.5703;gnomAD_exome_AFR=0.1305;gnomAD_exom
e_AMR=0.4852;gnomAD_exome_ASJ=0.5441;gnomAD_exome_EAS=0.6577;gnomAD_exome_FIN=0.6262;gnomAD_exome_NFE=0.6355;gnomAD_exome_OTH=0.5652;gnomAD_exome_SAS=0.5650;ALLELE_END;ANN=A|synonymous_variant|LOW|NOC2L|NOC2L|transcript|NM_015658.3|protein_coding|16/19|c.1843C>T|
p.Leu615Leu|1902/2800|1843/2250|615/749||,A|downstream_gene_variant|MODIFIER|SAMD11|SAMD11|transcript|NM_152486.2|protein_coding||c.*2094G>A|||||1666|;CSQ=A|upstream_gene_variant|MODIFIER|NOC2L|ENSG00000188976|Transcript|ENST00000496938|processed_transcript||||||
|||||1|685|-1|HGNC|24517||||||0.887,A|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000342066|protein_coding|||||||||||1|1672|1|HGNC|28706|YES||CCDS2.2|NM_152486.2||,A|synonymous_variant|LOW|NOC2L|ENSG00000188976|Transcript|ENST00000327
044|protein_coding|16/19||ENST00000327044.6:c.1843C>T|ENST00000327044.6:c.1843C>T(p.%3D)|1893|1843|615|L|Ctg/Ttg||1||-1|HGNC|24517|YES||CCDS3.1|NM_015658.3||0.887,A|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000464948|retained_intron
|||||||||||1|3355|1|HGNC|28706||||||,A|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000466827|retained_intron|||||||||||1|3445|1|HGNC|28706||||||,A|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000474461|reta
ined_intron|||||||||||1|3253|1|HGNC|28706||||||,A|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000455979|protein_coding|||||||||||1|1988|1|HGNC|28706||||||,A|non_coding_transcript_exon_variant&non_coding_transcript_variant|MODIFIER|NOC
2L|ENSG00000188976|Transcript|ENST00000483767|retained_intron|2/5||ENST00000483767.1:n.699C>T||699||||||1||-1|HGNC|24517||||||0.887,A|downstream_gene_variant|MODIFIER|SAMD11|ENSG00000187634|Transcript|ENST00000478729|processed_transcript|||||||||||1|4074|1|HGNC|2
8706||||||,A|non_coding_transcript_exon_variant&non_coding_transcript_variant|MODIFIER|NOC2L|ENSG00000188976|Transcript|ENST00000477976|retained_intron|14/17||ENST00000477976.1:n.3290C>T||3290||||||1||-1|HGNC|24517||||||0.887,A|downstream_gene_variant|MODIFIER|SA
MD11|ENSG00000187634|Transcript|ENST00000341065|protein_coding|||||||||||1|1672|1|HGNC|28706||||||   GT:AD:DP:GQ:PL:SB       0/1:11,14,0:25:99:361,0,319,754,360,754:9,2,10,4

**Comment by kaichop** [comment]
Please read FAQ #1 and provide details. Your version is also one and half year old now that should be updated first.
