### ISSUE TITLE
Error running system commands

### ISSUE THREAD

**Issue by surakshavinod** [WGLab/doc-ANNOVAR#215]
Hi, I'm using Annovar to annotate my VCF file and I'm running into an error. Please find below the command and the errors:

**Command:**
`perl table_annovar.pl <input.recode.vcf> humandb/ -buildver hg38 -out myanno -remove -protocol refGene,cytoBand,dbnsfp30a -operation g,r,f -nastring . -vcfinput`

**Errors:**
> Error running system command: <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile myanno.refGene -exonsort -nofirstcodondel myanno.avinput humandb/>
> Error running system command: <table_annovar.pl myanno.avinput humandb/ -buildver hg38 -outfile myanno -remove -protocol refGene,cytoBand,dbnsfp30a -operation g,r,f -nastring . -otherinfo>

Thanks,
Suraksha

**Comment by kaichop** [comment]
What is the actual command and the actual error message?

**Comment by surakshavinod** [comment]
**Command used:** 
`perl table_annovar.pl input.recode.vcf humandb/ -buildver hg38 -out myanno -remove -protocol refGene,cytoBand,dbnsfp30a -operation g,r,f -nastring . -vcfinput`

This the error log (Please note I have replaced the actual numbers with <>):

> NOTICE: the --polish argument is set ON automatically (use --nopolish to change this behavior)
> 
> NOTICE: Running with system command <convert2annovar.pl  -includeinfo -allsample -withfreq -format vcf4 input.recode.vcf > myanno.avinput>
> NOTICE: Finished reading <> lines from VCF file
> NOTICE: A total of <> locus in VCF file passed QC threshold, representing <> SNPs (<> transitions and <> transversions) and <> indels/substitutions
> NOTICE: Finished writing allele frequencies based on <> SNP genotypes (<> transitions and <> transversions) and <> indels/substitutions for <> samples
> 
> NOTICE: Running with system command <table_annovar.pl myanno.avinput humandb/ -buildver hg38 -outfile myanno -remove -protocol refGene,cytoBand,dbnsfp30a -operation g,r,f -nastring . -otherinfo>
> NOTICE: the --polish argument is set ON automatically (use --nopolish to change this behavior)
> -----------------------------------------------------------------
> NOTICE: Processing operation=g protocol=refGene
> 
> NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile myanno.refGene -exonsort -nofirstcodondel myanno.avinput humandb/>
> NOTICE: Output files are written to myanno.refGene.variant_function, myanno.refGene.exonic_variant_function
> NOTICE: Reading gene annotation from humandb/hg38_refGene.txt ... Done with <> transcripts (including <> without coding sequence annotation) for <> unique genes
> Error running system command: <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile myanno.refGene -exonsort -nofirstcodondel myanno.avinput humandb/>
> Error running system command: <table_annovar.pl myanno.avinput humandb/ -buildver hg38 -outfile myanno -remove -protocol refGene,cytoBand,dbnsfp30a -operation g,r,f -nastring . -otherinfo>
> 

Could there be something wrong with the VCF file format itself?

Thanks,
Suraksha

**Comment by kaichop** [comment]
If your file is huge (like 10 million variants, or thousands of samples),
then it is possible that there is a out of memory error. Since you masked
the numbers below it is hard to tell.
However, you could just run the system command yourself and see output
(perhaps this gives some clue). This command seems to be the one that leads
to error message.

annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile
myanno.refGene -exonsort -nofirstcodondel myanno.avinput humandb

**Comment by kaichop** [comment]
Thank you for letting me know.
