### ISSUE TITLE
Which version of 1000G database is used for wANNOVAR?

### ISSUE THREAD

**Issue by biofisherman** [WGLab/doc-ANNOVAR#218]
Thank you very much for your excellent tool.

I have two questions as follow:

1. Which version of the 1000G database is used for wANNOVAR?

2. Which 1000g database should I use for the local run?
I tried downloading the "1000g2015aug (6 data sets)", running table_annovar.pl, and got an error: "Error: the required database file humandb/hg19_1000g2015aug.txt does not exist.". I do see multiple 1000g2015-related files in the downloaded database folder. 

How do you think I should deal with this issue?

Thanks,

Weiyan

--

**Comment by kaichop** [comment]
There are multiple versions as described in
https://annovar.openbioinformatics.org/en/latest/user-guide/download/
Please show the actual command. Did you actually download the data sets
before running table_annovar? Also you need to specify the subpopulation
such as 1000g2012apr_asn, instead of 1000g2012apr only.

**Comment by biofisherman** [comment]
Thank you very much for your quick response!

I tested it out as you suggested.

I have to specify the exact names of the downloaded database files. For example, I must use `ALL.sites.2014_10,EAS.sites.2014_10,...` NOT the table name: `1000g2014aug`.

Best,

Weiyan

**Comment by kaichop** [comment]
No, you cannot use  ALL.sites.2014_10. FAQ #4 explains this problem.

**Comment by nanu23333** [comment]
may I ask which version of ANNOVAR supports ALL.sites.2015_08? @kaichop

**Comment by nanu23333** [comment]
and how can I download ALL.sites.2015_08 database? since I try 

```../annotate_variation.pl -buildver hg38 -downdb -webfrom annovar ALL.sites.2015_08 .```

but I got an error

```NOTICE: Web-based checking to see whether ANNOVAR new version is available ... Done
NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/***/hg38_ALL.sites.2015_08.txt.gz ... Failed
NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/***/hg38_ALL.sites.2015_08.txt.idx.gz ... Failed
WARNING: Some files cannot be downloaded, including http://www.openbioinformatics.org/annovar/***/hg38_ALL.sites.2015_08.txt.gz, http://www.openbioinformatics.org/annovar/***/hg38_ALL.sites.2015_08.txt.idx.gz ```

I will be grateful if you help me out!

**Comment by kaichop** [comment]
all versions of annovar support it, but you have to use the
keyword 1000g2015aug_all and so on. Read FAQ #4
https://annovar.openbioinformatics.org/en/latest/misc/faq/

**Comment by nanu23333** [comment]
Thanks for your timely reply!!!!
I will try again!
