### ISSUE TITLE
Access to previous versions of ANNOVAR

### ISSUE THREAD

**Issue by senbaikang** [WGLab/doc-ANNOVAR#219]
Hello Prof. Wang,

Thank you for making ANNOVAR available.

I wonder if it is possible to have access to previous versions of ANNOVAR, specifially, to version 2020 Jun. 08?

Thank you in advance for your help.

Best regards,
Senabi

**Comment by kaichop** [comment]
This is the latest version already.

**Comment by senbaikang** [comment]
Thank you for the reply!

How about previous versions of databases, such as hg19_refGene and hg19_ensGene? Are they archived somewhere that I can download from?

Thank you in advance!

**Comment by kaichop** [comment]
The last update of refGene is 2020 in UCSC and there is no new version
since then (see
https://annovar.openbioinformatics.org/en/latest/user-guide/download/)
For Gencode (which is ensGene, you can download the version 40 and 41 using
the ensGene40 ensGene41 keyword. I did not prepare v42. The current version
is v43.

**Comment by senbaikang** [comment]
Great! Thank you for your information :)

I am actually looking for the ensGene database built around 2020~2021 for consistency reasons, and I couldn't find any versions earlier than ensGene40 on the Annovar website. Do you by any chance have them backed up somewhere?

Thank you again for your kind help!

Best,
Senbai

**Comment by kaichop** [comment]
you can check https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ to
find all the wgEncodeGencode*** files, and then determine which one you
need. Then you can build the annovar database yourself easily using
instructions in the website.
