### ISSUE TITLE
why ANNOVAR report a 3-bp deletion as 2 amino-acid deletion

### ISSUE THREAD

**Issue by linkluck** [WGLab/doc-ANNOVAR#23]
For example "chr9 139390944 TGTG T" (hg19 coordinate) is annotated as  "AAChange.refGene=NOTCH1:NM_017617:exon34:c.7244_7246del:p.2415_2416del".But I think it should be annotated as "AAChange.refGene=NOTCH1:NM_017617:exon34:c.7244_7246:p.2415_2416delinsQ"

**Comment by kaichop** [comment]
please read FAQ #1 and provide details.
