### ISSUE TITLE
prepare_annovar_user.pl not working with COSMIC version 99

### ISSUE THREAD

**Issue by ValerieCrolley** [WGLab/doc-ANNOVAR#240]
Hi - thank you so much for your hard work on this tool!

I've having a minor issue with getting prepare_annovar_user.pl to run with COSMIC version 99. I'm using the newest version of prepare_annovar_user.pl from 19th Feb 2024, but when I run the following:

./prepare_annovar_user.pl -dbtype cosmic Cosmic_GenomeScreensMutant_v99_GRCh38.tsv.gz -vcf Cosmic_GenomeScreensMutant_v99_GRCh38.vcf.gz  >> COSMIC/hg38_cosmic99.txt

I get the following error:

Error: COSMIC MutantExport format error: column 17 or 18 or 12 should be 'Mutation ID' or 'GENOMIC_MUTATAION_ID' or 'ID_NCV', or at least 'GENOMIC_MUTATAION_ID' should be present in the header line

Looking at the COSMIC 99, it looks like the MUTATION_ID column is now column 9, and GENOMIC_MUTATION_ID is now column 7, so neither are in columns 17, 18 or 12 . I could move the column, but I think that would probably break other parts of the prepare_annovar_user.pl script. Would it be possible to update prepare_annovar_user.pl so it works with COSMIC v99?

**Comment by kaichop** [comment]
First, please use "gunzip" to unzip these files, or use shell
re-direction to handle this on the fly depending on which shell you are
using.

The script was recently updated to handle COSMIC v99. Are you sure you are
using the latest version at
https://www.openbioinformatics.org/annovar/download/prepare_annovar_user.pl?

**Comment by ValerieCrolley** [comment]
Thank you for getting back to me so quickly! The version from your link works - I'm not sure why the version from your website wasn't.

Have a lovely evening!
