### ISSUE TITLE
ANNOVAR filter an important complext mutation

### ISSUE THREAD

**Issue by lituan** [WGLab/doc-ANNOVAR#25]
Hi

I use ANNOVAR to annotate a vcf , but it filter an important mutaion, which is as follows:

chr7   55242468   .   ATTAAGAGAAGCAA  AC

**Comment by kaichop** [comment]
please read FAQ #1

**Comment by lituan** [comment]
Hi, Professor Wang

my new question is, annovar only give 'c.' but did not give 'p.' for complex variants

my command is as follows:

 ./table_annovar.pl test.vcf humandb/ -buildver hg19 -out test -remove -protocol refGene -operation g -vcfinput

one input variant is:
chr2	29445212	.	GA	AT	.	.	.

annovar output is:
chr2	29445212	.	GA	AT	.	.	.;ANNOVAR_DATE=2018-04-16;Func.refGene=exonic;Gene.refGene=ALK;GeneDetail.refGene=.;ExonicFunc.refGene=nonframeshift_substitution;AAChange.refGene=ALK:NM_004304:exon22:c.3512_3513AT;ALLELE_END

**Comment by lituan** [comment]
I got the right result, Thank you very much
