### ISSUE TITLE
rs snp allele frequency deficiency

### ISSUE THREAD

**Issue by zhq90** [WGLab/doc-ANNOVAR#26]
The dataset exac03 have no allele frequency for SNP rs2504779, which was shown in vcf file from ExAC official website(AF=0.178).  The variant site is thought to be a common variants which should be filtered out, but the missing AF cause some problems to my analysis.
And I think there were many missing allele frequency in exac03 dataset, how can I deal with this problem?

**Comment by kaichop** [comment]
please read FAQ #1 and provide details.

**Comment by zhq90** [comment]
What I mean is that hg38 and hg19 coordinates have some inconsistency, there is some missing allele frequency at the inconsistent sites between two version with ExAC dataset, but the corresponding amino acid change is the same. So is there any solutions to the problem?

**Comment by kaichop** [comment]
please read FAQ #1 and provide details.

**Comment by zhq90** [comment]
For example, the rs79881008 have the allele frequency information in the ExAC brower(AF = 0.2106, ref/alt = G/A), but in the Annovar exac03 annotation results, there is no AF information at the rs79881008.

**Comment by kaichop** [comment]
rs79881008 does not mean anything, it is not an identifiable piece of
information. Read
http://annovar.openbioinformatics.org/en/latest/articles/dbSNP/
In addition exac browser may have version 1.0, but exac03 is version 0.3.
