### ISSUE TITLE
Need Assistance with ANNOVAR annotate_variation.pl Command

### ISSUE THREAD

**Issue by iegab** [WGLab/doc-ANNOVAR#265]
Hello everyone,

I am currently trying to run the following ANNOVAR command:
perl annovar/annotate_variation.pl -build hg38 -out /file_gencode_v38 -dbtype ensGene

However, I'm encountering an issue that isn't providing any clear direction on how to proceed. I've also tried running the suggested commands provided in the error message, but unfortunately, I haven't had any success.
Here is a summary of the issue:

Error: The gene annotation database /file/hg38_ensGene.txt does not exist. Please use 'annotate_variation.pl --downdb ensGene /file -build hg38' to download the database.
Then,
NOTICE: Web-based checking to see whether ANNOVAR new version is available ... Done
NOTICE: Downloading annotation database http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/ensGene.txt.gz ... Failed
WARNING: Some files cannot be downloaded, including http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/ensGene.txt.gz
---------------------------ADDITIONAL PROCEDURE---------------------------
--------------------------------------------------------------------------
NOTICE: the FASTA file for the genome is not available to download but can be generated by the ANNOVAR software.
PLEASE RUN THE FOLLOWING TWO COMMANDS CONSECUTIVELY TO GENERATE THE FASTA FILES (you may need to change -seqdir to -seqfile for some genomes):

	annotate_variation.pl --buildver hg38 --downdb seq /file/hg38_seq
	retrieve_seq_from_fasta.pl /file/hg38_ensGene.txt -seqdir /file/hg38_seq -format ensGene -outfile /file/hg38_ensGeneMrna.fa
The last error after running these two codes are :
1- NOTICE: Web-based checking to see whether ANNOVAR new version is available ... Done
NOTICE: Downloading annotation database http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/chromFa.zip ... Failed
NOTICE: Downloading annotation database http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/chromFa.tar.gz ... Failed
NOTICE: Downloading annotation database http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/hg38.chromFa.tar.gz ... OK
NOTICE: Downloading annotation database http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz ... OK
NOTICE: Uncompressing downloaded files
NOTICE: Finished downloading annotation files for hg38 build version, with files saved at the '/file' directory.
2- Error: cannot read from regionfile /file/hg38_ensGene.txt: No such file or directory

Despite trying these steps, I'm still unable to successfully proceed. Could anyone please provide guidance on how to resolve this issue or any insights into what might be going wrong? Your help would be highly appreciated!

Thank you so much!
Best

**Comment by kaichop** [comment]
You need to use
perl annovar/annotate_variation.pl -build hg38 -downdb ensGene -webfrom
annovar .
to download the database first

There are two problems with your command: (1) you did not add "-webfrom
annovar" (2) You cannot use "/file_gencode_v38" in your command because
this is a directory under the root, and in most cases you do not have write
permission to a root directory.
I hope this helps.

**Comment by iegab** [comment]
Hi Kai,

It worked and I was able to generate the files. I am greatly appreciative of your prompt reply and help!

Best,
Iman
