### ISSUE TITLE
Downloading annotation database hg38_dbnsfp33a.txt.gz ... Failed

### ISSUE THREAD

**Issue by gpcr** [WGLab/doc-ANNOVAR#27]
```
perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar dbnsfp33a humandb/
NOTICE: Web-based checking to see whether ANNOVAR new version is available ... Done
NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg38_dbnsfp33a.txt.gz ... Failed
NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg38_dbnsfp33a.txt.idx.gz ... OK
NOTICE: Uncompressing downloaded files
NOTICE: Finished downloading annotation files for hg38 build version, with files saved at the 'humandb' directory
WARNING: Some files cannot be downloaded, including http://www.openbioinformatics.org/annovar/download/hg38_dbnsfp33a.txt.gz

```
Any alternatives to download dbnsfp33a?

**Comment by kaichop** [comment]
you can download it yourself using the URL. There are many software tools
that support multi-threaded download and support breakpoint resumption that
you may want to use if your internet connection is not reliable/consistent
enough.

**Comment by gpcr** [comment]
I downloaded using wget and ran the dbnsfp33a   filter step and It is taking ~5 hours to complete one exome, so was wondering if any corruption in that large file 
BTW do you have MD5 file to check hg38_dbnsfp33a.txt.gz

**Comment by kaichop** [comment]
read FAQ #1 and provide details of error/warning message. (but in general,
if it did not say using index file then the file is definitely corrupted
and will also result in very long run time)

use avdblist as dbtype to download the information. However, the file no
longer contains MD5 and only contains file size/date information. It can
still be helpful to diagnose download issue though. If file is corrupted,
gz should also report a warning message when you uncompress.
