### ISSUE TITLE
HGVS annotation for intronic variants

### ISSUE THREAD

**Issue by apaytuvi** [WGLab/doc-ANNOVAR#30]
Hi,

first of all, thank you for maintaining this great piece of software! I am trying to annotate some variants using this command:

```
perl ./annovar/table_annovar.pl --thread 30 final.vcf ./annovar/humandb/ -buildver hg19 -out final_annotation -remove -protocol refGene.mit,clinvar_20170905.mit,exac03,ALL.sites.2015_0_mod8,esp6500siv2_all,avsnp150.mit,gnomad_exome,gnomad_genome -operation g,f,f,f,f,f,f,f -nastring . -vcfinput
```

However, intronic variants are not annotated using the HGVS standard. How might I obtain these HGVS annotations?

Thanks.

**Comment by kaichop** [comment]
The "ALL.sites.2015_0_mod8" should not be used (please read FAQ #4)

Intronic variants cannot be annotated with hgvs, unless you set a very high
-splicing_threshold as the first argument in the -arg



perl ./annovar/table_annovar.pl --thread 30 final.vcf
./annovar/humandb/ -buildver hg19 -out final_annotation -remove
-protocol refGene.mit,clinvar_20170905.mit,exac03,1000g2015aug_all,esp6500siv2_all,avsnp150.mit,gnomad_exome,gnomad_genome
-operation g,f,f,f,f,f,f,f -nastring . -vcfinput -arg '-splicing
100',,,,,,
