### ISSUE TITLE
ExonicFunc type is "nonframeshift substitution", but AAChange is ":p.,"

### ISSUE THREAD

**Issue by haiwufan** [WGLab/doc-ANNOVAR#31]
Hi developer
I find some variants is "nonframeshift substitution", but the AAChange column show "":p.,".
How can I solve this problem?
![default](https://user-images.githubusercontent.com/33748647/39918737-016ebee4-5544-11e8-80d7-b9ffe3eec4c3.png)

**Comment by kaichop** [comment]
Please read FAQ #1 and provide missing information.
