### ISSUE TITLE
the same mutations have two different rs

### ISSUE THREAD

**Issue by wittying** [WGLab/doc-ANNOVAR#32]
1. the same mutaions have two different rsID in  hg19_avsnp150.txt. for example:
1       10352   10352   T       TA      rs145072688
1       10352   10352   T       TA      rs555500075
2. I search rs145072688 and rs555500075 in dbsnp database:
rs555500075  means 1:10352:T:TA
rs145072688 means 1:10353:A:AC
3. dbSNP's own VCF file: ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b150_GRCh37p13/VCF/All_20170710.vcf.gz has this problem. but ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/All_20180423.vcf.gz has no this problem. Could you please update the avsnp to v151?
thank you very much!

**Comment by kaichop** [comment]
There is nothing wrong with it. rsid is not identifiable and should never be used in any genetic analysis in variant. It is at most a locus identifier and I write an article specifically about it in annovar website.
