### ISSUE TITLE
Not updated exonic variant funcion in documentation

### ISSUE THREAD

**Issue by gotolino** [WGLab/doc-ANNOVAR#35]
There are missing values in the documentation of annovar for the exonic variant function: http://annovar.openbioinformatics.org/en/latest/user-guide/gene/

The values that I found looking around in annotate_variation.pl (I am not sure if its all there):
- frameshift insertion
- frameshift deletion
- frameshift substitution
- stopgain
- stoploss
- nonframeshift insertion
- nonframeshift deletion
- nonframeshift substitution
- nonsynonymous SNV
- synonymous SNV
- unknown

**Comment by kaichop** [comment]
These are the same as
http://annovar.openbioinformatics.org/en/latest/user-guide/gene/#output-file-2-refseq-gene-annotation
what are missing?
