### ISSUE TITLE
How to integrate hg38_multianno.csv  back to bcf file? 

### ISSUE THREAD

**Issue by smangul1** [WGLab/doc-ANNOVAR#36]
Does ANNOVAR offer the possibility to integrate hg38_multianno.csv  back into original bcf file?

Thanks,
Serghei

**Comment by smangul1** [comment]
Great! It works!  

Is it expected to get no categories for intergenic variants? See example below

chr22   10514536        .       T       A       31.4849 .       VDB=0.074936;SGB=-0.511536;MQ0F=0;MQ=23;MQSB=1;RPB=1;MQB=1;BQB=1;DP=25;DP4=0,1,20,3;AN
=18;AC=18;ANNOVAR_DATE=2018-04-16;Func.refGene=intergenic;Gene.refGene=NONE\x3bLOC102723780;GeneDetail.refGene=dist\x3dNONE\x3bdist\x3d426061;ExonicFunc.refGene=.;AAChange.refGene=.;cytoBand=22p11.2;SIFT_score=.;SIFT_pred=.;Polyphen2_HDIV_score=.;Polyphen2_HDIV_pred=.;Polyphen2_HVAR_score=.;Polyphen2_HVAR_pred=.;LRT_score=.;LRT_pred=.;MutationTaster_score=.;MutationTaster_pred=.;MutationAssessor_score=.;MutationAssessor_pred=.;FATHMM_score=.;FATHMM_pred=.;PROVEAN_score=.;PROVEAN_pred=.;VEST3_score=.;CADD_raw=.;CADD_phred=.;DANN_score=.;fathmm-MKL_coding_score=.;fathmm-MKL_coding_pred=.;MetaSVM_score=.;MetaSVM_pred=.;MetaLR_score=.;MetaLR_pred=.;integrated_fitCons_score=.;integrated_confidence_value=.;GERP++_RS=.;phyloP7way_vertebrate=.;phyloP20way_mammalian=.;phastCons7way_vertebrate=.;phastCons20way_mammalian=.;SiPhy_29way_logOdds=.;ALLELE_END  GT:PL 

Serghei

**Comment by kaichop** [comment]
what does " no categories" mean?

**Comment by smangul1** [comment]
Sorry for not being more explicit. I mean many categories including CADD are empty. "CADD_raw=." 

Thanks,
Serghei

**Comment by kaichop** [comment]
It means the CADD_raw score is not available for this variant. This is not
related to intergneic variant. Almost all variants should have CADD Scores.
