### ISSUE TITLE
minqueryfrac is not compatible with geneanno

### ISSUE THREAD

**Issue by wisekh6** [WGLab/doc-ANNOVAR#37]
Hello,

I wonder if you let me know how to set **minqueryfrac* when using **geneanno**.
Shown below are two scripts that I tested.

Thank you in advance,

hk

**Run successfully**
`./annotate_variation.pl -geneanno -buildver hg19 -dbtype knownGene -outfile myanno.knownGene -exonsort ./avinput.txt ./annovar/humandb/`

**Failed**
`./annotate_variation.pl -geneanno -buildver hg19 -dbtype knownGene -outfile myanno.knownGene --minqueryfrac 0.1 -exonsort ./avinput.txt ./annovar/humandb/`

**Comment by kaichop** [comment]
It is a parameter for overlap only, so it is a region-based annotation, not
gene-based annotation.

**Comment by wisekh6** [comment]
Thanks for your quick response.

Two quick questions:
1. Would you confirm that gene annotation is based on any overlap (>=1bp) with query?
2. There is no similar parameter for gene-based annotation? 

Thank you in advance,

**Comment by kaichop** [comment]
1. gene annotation does not care about overlap. It tells you how a gene is
affected by a mutation.
2. No, it does not make sense to have overlap in gene annotation.
