### ISSUE TITLE
How could I Convert this format to avinput

### ISSUE THREAD

**Issue by y842739756** [WGLab/doc-ANNOVAR#38]
Dear Dr.Wang
I use the _**Breakdancer**_ to identify SVs and the output format like this 
#Chr1   Pos1    Orientation1    Chr2    Pos2    Orientation2    Type    Size    Score   num_Reads       num_Reads_lib   danban.bam

- original_scaffold_197   5227    21+21-  original_scaffold_197   5355    21+21-  INS     -360    33      21      danban.bam|21   NA
- original_scaffold_197   6370    33+33-  original_scaffold_197   6664    33+33-  INS     -328    43      34      danban.bam|34   NA
- original_scaffold_197   8436    0+0-    original_scaffold_197   9379    16+16-  INS     -327    38      16      danban.bam|16   5.85

for example ,the 1st line means An 360 bp insertion detected by BreakDancer between scaffold_197:5227 and scaffold_197:5355 with 21 supporting read pairs,and a confidence score of 33. this software also said that "Real SV breakpoints are expected to reside within the predicted boundaries."

①how could i convert this format to avinput,may i use this format to describe this INS like the annovar README and worked in gene-based annonation?

- original_scaffold_197 5227 5355 0 0 comments:a 360bp insertion between there

②and how could i describe the  inter-chromosomal translocation between different Chr ,and intra-chromosomal translocation?
③I noticed that **_BreakDancer_** could use the .bed format output ,.i tried to convert .bed to .vcf but failed ,and **_annovar_** don't said support .bed format, so i can't use convert2annovar.pl convert bedfile to avinput ,right?
 
                                                                                                            Thanks for your time

**Comment by kaichop** [comment]
You can manually reformat this to standard avinput (the one that you showed
is okay to use). But to annotate the variants, make sure that your FASTA
file has the same scaffold names not chromosome names.
There is no good way to specify inter-chromosomal translocations. You have
to treat it as two separate indels. If you want to know the new fusion gene
that is expressed, then it has to be done manually (i.e. check that the
correct splice site is present, then add the exons manually into a new
protein).
BED is easy to convert to avinput (right now you do not have ref/alt in BED
so you can just use 0 as ref and alt).

**Comment by y842739756** [comment]
Thank you Dr.Wang
    That's helpful ,thank you sir.
