### ISSUE TITLE
A question about clinvar 20180603 lose one significant position!!

### ISSUE THREAD

**Issue by Kami0King** [WGLab/doc-ANNOVAR#40]
Honored Gentlemen, I found  a significant position(chr9:136501794) doesn't appear in 20180603 version clinvar, but it still been found in 20170905 version clinvar. When I go to Clinvar website, there has the position information, and show its a pathogenetic dbsnp, so I'm confused!

**Comment by kaichop** [comment]
Please read FAQ #1 and provide details.
