### ISSUE TITLE
AA change conflicts with cdna change

### ISSUE THREAD

**Issue by hy101** [WGLab/doc-ANNOVAR#42]
> 7	55242464	.	AGGAATTAAGAGAAGC	A	.	.	DP=1185;ECNT=1;POP_AF=4.06e-06;TLOD=45.87;ANNOVAR_DATE=2018-04-16;Func.refGene=exonic;Gene.refGene=EGFR;GeneDetail.refGene=.;ExonicFunc.refGene=**nonframeshift_deletion**;AAChange.refGene=EGFR:NM_005228:exon19:**c.2235_2249del:p.745_750del**;ALLELE_END	

I got an nonframeshift_deletion , 15bp in cdna but 6aa in protein. 

![image](https://user-images.githubusercontent.com/22981374/46254073-32cd2100-c4bc-11e8-88ea-ae5f6879e6aa.png)

It should be p.746_750del 
Is there any thing wrong?

**Comment by kaichop** [comment]
I have tested the latest ANNOVAR and it indeed shows NM_005228:exon19:c.2235_2249del:p.E746_A750del. It will be released soon.
