### ISSUE TITLE
index file out of date

### ISSUE THREAD

**Issue by Xiaohuaniu0032** [WGLab/doc-ANNOVAR#44]
when run the annotation, I got a warning:
`WARNING: Your index file hg19_clinvar_20170130.txt.idx is out of date a
nd will not be used. ANNOVAR can still generate correct results without index file.`

I want to know why this warning happened and how Annovar distinguish the index file is `out of date`?last problem: if the index file is out of date, what influence will occur? will the speed slow down?

many thanks here

**Comment by kaichop** [comment]
it could be a corrupted file that you need to download again. It is based o
file size to judge if the file is out of date.

**Comment by Xiaohuaniu0032** [comment]
ok, thank you. i checked the file and quite find the problem is the col 3 in the head of idx is not equal to the real file size.

here is another question about `construct the index file for custom database file`  can you send me a copy of the index script? i had send you an email about 7 hours ago but did not get your reply. thanks a lot.

**Comment by kaichop** [comment]
I did not receive your email, only this github message.

**Comment by Xiaohuaniu0032** [comment]
oooh, i send the email to `kaiwang@usc.edu`, i am not sure what happened. can you send me a copy of the index script to my email `lffu_0032@outlook.com`?(the first letter is the lower case of `L`)

many thanks for your kindly help:)

**Comment by Xiaohuaniu0032** [comment]
I had sent the email again to your current chop.edu email, please check and thanks a lot.
