### ISSUE TITLE
Can't download Annovar

### ISSUE THREAD

**Issue by delphinedouillet** [WGLab/doc-ANNOVAR#46]
Hi,

I have been trying to download annovar ( by going to this webpage 'www.openbioinformatics.org/annovar/annovar_download.html') and this page is never loading. So I also tried by using this command line : 'wget http://www.openbioinformatics.org/annovar/download/annovar.latest.tar.gz.mirror' and got the same issue. Is the website in maintenance?

Thank you very much for your help

Best,

Delphine

**Comment by kaichop** [comment]
server is temporarily down at the moment.

**Comment by yangyangclover** [comment]
the same problem...come on！server！

**Comment by sneakyness** [comment]
It might be a good idea to make the "server is down" notice larger on the documentation page, and link to this GitHub issue

**Comment by kaichop** [comment]
Please note that the server is back online a few days ago and I forgot to update the issue. Thank you.
