### ISSUE TITLE
Annotate using .gtk file

### ISSUE THREAD

**Issue by e-jorsboe** [WGLab/doc-ANNOVAR#47]
Hi,

I have followed this link:

http://annovar.openbioinformatics.org/en/latest/user-guide/gene/#what-about-gff3-file-for-new-species

In order to be able to annotate from a gff3 file. However I cannot really make annovar work with this database, so what command exactly should I run to annotate this:

AT_refGene.txt
AT_refGeneMrna.fa
input.sorted.vcf.uniqShort

I have tried something like this:
perl annotate_variation.pl -out ex1 -dbtype  AT_refGene -vcfinput input.sorted.vcf.uniqShort

**Comment by kaichop** [comment]
You need to add -geneanno to indicate that this is a gene-based annotation.
The build is AT, and the dbtype is refGene. If you use annotate_variation,
you cannot do -vcfinput argument which is only for table_annovar.

Just read and follow quick start-up guide and exercise to learn the basic
first, and then read the gene annotation page. Everything is explained in
great details.
