### ISSUE TITLE
Unable to download regsnpintron

### ISSUE THREAD

**Issue by croct** [WGLab/doc-ANNOVAR#48]
Hi,
I am unable to download the regsnpintron database.  The command & the corresponding error are shown below.  I was able to download other databases without any problems.  Is the regsnpintron database still available?
Thanks,
Mike

./annotate_variation.pl -downdb -buildver hg19 -webfrom annovar regsnpintron humandb/
NOTICE: Web-based checking to see whether ANNOVAR new version is available ... Done
NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg19_regsnpintron.txt.gz ... Failed
NOTICE: Downloading annotation database http://www.openbioinformatics.org/annovar/download/hg19_regsnpintron.txt.idx.gz ... Failed
WARNING: Some files cannot be downloaded, including http://www.openbioinformatics.org/annovar/download/hg19_regsnpintron.txt.idx.gz, http://www.openbioinformatics.org/annovar/download/hg19_regsnpintron.txt.gz

**Comment by kaichop** [comment]
This database is uploaded again and should be available now. Please try
again.

**Comment by croct** [comment]
Downloading now.  Thanks.
