### ISSUE TITLE
downdb argument fails

### ISSUE THREAD

**Issue by shiva-g** [WGLab/doc-ANNOVAR#53]
annotate_variation.pl --downdb gnomad_genome -buildver hg38 humandb/
NOTICE: Web-based checking to see whether ANNOVAR new version is available ... Done
NOTICE: Downloading annotation database http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/gnomad_genome.txt.gz ... Failed
WARNING: Some files cannot be downloaded, including http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/gnomad_genome.txt.gz

The same error is true for other databases too

**Comment by kaichop** [comment]
Add "-webfrom annovar". Read FAQ #3

**Comment by shiva-g** [comment]
Thanks! It works
