### ISSUE TITLE
frameshift insertion HGVS difference between Annovar and VEP

### ISSUE THREAD

**Issue by lihb001** [WGLab/doc-ANNOVAR#54]
Dear Developers!
annovar_2018-04-16
When I annotate my vcf, we found a insertion variant event with different HGVS description between Annovar and VEP.
This insertion variant is as below:
chr6    49457714     49457714    -    AA

Annovar Result:

![image](https://user-images.githubusercontent.com/41052418/53724987-0de33c80-3ea6-11e9-9164-f1f8527f8da9.png)

HGVS:   p.Asp244Leufs*38

VEP online Result:
![image](https://user-images.githubusercontent.com/41052418/53725746-8f879a00-3ea7-11e9-9567-30726979129a.png)

HGVS:   p.Asp244LeufsTer39

Difference:   Annovar Ter38 but VEP Ter39. 
When I check article about this variant record, found most of HGVS was record as Ter39.

What causes this difference of protein HGVS? Which one is correct?

**Comment by lihb001** [comment]
The Reference Genome version is hg38.

**Comment by kaichop** [comment]
You can print out the new coding sequence using coding_change.pl in ANNOVAR.

coding_change.pl temp.refGene.exonic_variant_function
humandb/hg38_refGene.txt humandb/hg38_refGeneMrna.fa

The results are show:

>line1 NM_000255 c.729_730insTT p.D244Lfs*38 protein-altering  (position
244-750 changed from
DIFEYTAKHMPKFNSISISGYHMQEAGADAILELAYTLADGLEYSRTGLQAGLTIDEFAPRLSFFWGIGMNFYMEIAKMRAGRRLWAHLIEKMFQPKNSKSLLLRAHCQTSGWSLTEQDPYNNIVRTAIEAMAAVFGGTQSLHTNSFDEALGLPTVKSARIARNTQIIIQEESGIPKVADPWGGSYMMECLTNDVYDAALKLINEIEEMGGMAKAVAEGIPKLRIEECAARRQARIDSGSEVIVGVNKYQLEKEDAVEVLAIDNTSVRNRQIEKLKKIKSSRDQALAERCLAALTECAASGDGNILALAVDASRARCTVGEITDALKKVFGEHKANDRMVSGAYRQEFGESKEITSAIKRVHKFMEREGRRPRLLVAKMGQDGHDRGAKVIATGFADLGFDVDIGPLFQTPREVAQQAVDADVHAVGISTLAAGHKTLVPELIKELNSLGRPDILVMCGGVIPPQDYEFLFEVGVSNVFGPGTRIPKAAVQVLDDIEKCLEKKQQSV
to LTYLNIQQSTCQNLIQFQLVDTICRKQGLMPFWSWPIL)
MLRAKNQLFLLSPHYLRQVKESSGSRLIQQRLLHQQQPLHPEWAALAKKQLKGKNPEDLIWHTPEGISIKPLYSKRDTMDLPEELPGVKPFTRGPYPTMY
TFRPWTIRQYAGFSTVEESNKFYKDNIKAGQQGLSVAFDLATHRGYDSDNPRVRGDVGMAGVAIDTVEDTKILFDGIPLEKMSVSMTMNGAVIPVLANFI
VTGEEQGVPKEKLTGTIQNDILKEFMVRNTYIFPPEPSMKIIALTYLNIQQSTCQNLIQFQLVDTICRKQGLMPFWSWPIL*

So if you look a the D244 position, if it is changed from D
to LTYLNIQQSTCQNLIQFQLVDTICRKQGLMPFWSWPIL*.

I need to do some investigation whether this should be referred to as *fs38
or *fs39. The total length of new sequence is 39 (including stop codon),
but I am not sure whether the count start from L or T.

**Comment by lihb001** [comment]
Hi Developer,
I have check this mutation from different software or article.
summary like as below:

![image](https://user-images.githubusercontent.com/41052418/54504937-c6ae7e80-4970-11e9-9849-9cdeb589d794.png)

At the same time, I learn HGVS from this links:
https://www.hgvs.org/mutnomen/disc.html#frameshift

![image](https://user-images.githubusercontent.com/41052418/54505199-d1b5de80-4971-11e9-8ca9-f29a5e6b06f1.png)

Thanks!

**Comment by lihb001** [comment]
https://mutalyzer.nl/name-checker?description=NM_000255.3%3Ac.729_730insTT

![image](https://user-images.githubusercontent.com/41052418/54511928-7db8f300-498d-11e9-8753-eb6a37556fa8.png)

**Comment by kaichop** [comment]
Multiple users reported this issue and they used custom scripts to add the "fs" number by one. I have now updated the main table_annovar.pl file to handle the issue to be consistent with HGVS. I will release the updated version soon.
