### ISSUE TITLE
issue annotating GATK Haplotype Caller VCFs with table_annovar.pl

### ISSUE THREAD

**Issue by Tvira** [WGLab/doc-ANNOVAR#55]
Hello,

I'm attempting to annotate a vcf produced by GATK's haplotype caller using the following command: 
`##GATKCommandLine=<ID=HaplotypeCaller,CommandLine="HaplotypeCaller  --contamination-fraction-to-filter 0.0 --output K000049_1_lane_dupsFlagged_sm_tagged.vcf.gz --intervals /projects/trans_scratch/pedigree_calling/iTARGET_quad/vcfs/cromwell-executions/run_haplotypecaller_on_directory/509c4a23-7811-4d20-abc9-ce5bd7fe6d45/call-HaplotypeCallerGvcf_GATK4/shard-3/haplotypecaller.HaplotypeCallerGvcf_GATK4/3b9dfdc2-7cd5-4212-830c-d89263fe84fa/call-HaplotypeCaller/shard-97/inputs/1764290932/0097-scattered.intervals --input /projects/trans_scratch/pedigree_calling/iTARGET_quad/vcfs/cromwell-executions/run_haplotypecaller_on_directory/509c4a23-7811-4d20-abc9-ce5bd7fe6d45/call-HaplotypeCallerGvcf_GATK4/shard-3/haplotypecaller.HaplotypeCallerGvcf_GATK4/3b9dfdc2-7cd5-4212-830c-d89263fe84fa/call-HaplotypeCaller/shard-97/inputs/-1081452564/K000049_1_lane_dupsFlagged_sm_tagged.bam --reference /projects/trans_scratch/pedigree_calling/iTARGET_quad/vcfs/cromwell-executions/run_haplotypecaller_on_directory/509c4a23-7811-4d20-abc9-ce5bd7fe6d45/call-HaplotypeCallerGvcf_GATK4/shard-3/haplotypecaller.HaplotypeCallerGvcf_GATK4/3b9dfdc2-7cd5-4212-830c-d89263fe84fa/call-HaplotypeCaller/shard-97/inputs/-533456238/GRCh37-lite.fa  --emit-ref-confidence NONE --gvcf-gq-bands 1 --gvcf-gq-bands 2 --gvcf-gq-bands 3 --gvcf-gq-bands 4 --gvcf-gq-bands 5 --gvcf-gq-bands 6 --gvcf-gq-bands 7 --gvcf-gq-bands 8 --gvcf-gq-bands 9 --gvcf-gq-bands 10 --gvcf-gq-bands 11 --gvcf-gq-bands 12 --gvcf-gq-bands 13 --gvcf-gq-bands 14 --gvcf-gq-bands 15 --gvcf-gq-bands 16 --gvcf-gq-bands 17 --gvcf-gq-bands 18 --gvcf-gq-bands 19 --gvcf-gq-bands 20 --gvcf-gq-bands 21 --gvcf-gq-bands 22 --gvcf-gq-bands 23 --gvcf-gq-bands 24 --gvcf-gq-bands 25 --gvcf-gq-bands 26 --gvcf-gq-bands 27 --gvcf-gq-bands 28 --gvcf-gq-bands 29 --gvcf-gq-bands 30 --gvcf-gq-bands 31 --gvcf-gq-bands 32 --gvcf-gq-bands 33 --gvcf-gq-bands 34 --gvcf-gq-bands 35 --gvcf-gq-bands 36 --gvcf-gq-bands 37 --gvcf-gq-bands 38 --gvcf-gq-bands 39 --gvcf-gq-bands 40 --gvcf-gq-bands 41 --gvcf-gq-bands 42 --gvcf-gq-bands 43 --gvcf-gq-bands 44 --gvcf-gq-bands 45 --gvcf-gq-bands 46 --gvcf-gq-bands 47 --gvcf-gq-bands 48 --gvcf-gq-bands 49 --gvcf-gq-bands 50 --gvcf-gq-bands 51 --gvcf-gq-bands 52 --gvcf-gq-bands 53 --gvcf-gq-bands 54 --gvcf-gq-bands 55 --gvcf-gq-bands 56 --gvcf-gq-bands 57 --gvcf-gq-bands 58 --gvcf-gq-bands 59 --gvcf-gq-bands 60 --gvcf-gq-bands 70 --gvcf-gq-bands 80 --gvcf-gq-bands 90 --gvcf-gq-bands 99 --indel-size-to-eliminate-in-ref-model 10 --use-alleles-trigger false --disable-optimizations false --just-determine-active-regions false --dont-genotype false --max-mnp-distance 0 --dont-trim-active-regions false --max-disc-ar-extension 25 --max-gga-ar-extension 300 --padding-around-indels 150 --padding-around-snps 20 --kmer-size 10 --kmer-size 25 --dont-increase-kmer-sizes-for-cycles false --allow-non-unique-kmers-in-ref false --num-pruning-samples 1 --recover-dangling-heads false --do-not-recover-dangling-branches false --min-dangling-branch-length 4 --consensus false --max-num-haplotypes-in-population 128 --error-correct-kmers false --min-pruning 2 --debug-graph-transformations false --kmer-length-for-read-error-correction 25 --min-observations-for-kmer-to-be-solid 20 --likelihood-calculation-engine PairHMM --base-quality-score-threshold 18 --pair-hmm-gap-continuation-penalty 10 --pair-hmm-implementation FASTEST_AVAILABLE --pcr-indel-model CONSERVATIVE --phred-scaled-global-read-mismapping-rate 45 --native-pair-hmm-threads 4 --native-pair-hmm-use-double-precision false --debug false --use-filtered-reads-for-annotations false --bam-writer-type CALLED_HAPLOTYPES --dont-use-soft-clipped-bases false --capture-assembly-failure-bam false --error-correct-reads false --do-not-run-physical-phasing false --min-base-quality-score 10 --smith-waterman JAVA --use-new-qual-calculator false --annotate-with-num-discovered-alleles false --heterozygosity 0.001 --indel-heterozygosity 1.25E-4 --heterozygosity-stdev 0.01 --standard-min-confidence-threshold-for-calling 10.0 --max-alternate-alleles 6 --max-genotype-count 1024 --sample-ploidy 2 --num-reference-samples-if-no-call 0 --genotyping-mode DISCOVERY --genotype-filtered-alleles false --output-mode EMIT_VARIANTS_ONLY --all-site-pls false --min-assembly-region-size 50 --max-assembly-region-size 300 --assembly-region-padding 100 --max-reads-per-alignment-start 50 --active-probability-threshold 0.002 --max-prob-propagation-distance 50 --interval-set-rule UNION --interval-padding 0 --interval-exclusion-padding 0 --interval-merging-rule ALL --read-validation-stringency SILENT --seconds-between-progress-updates 10.0 --disable-sequence-dictionary-validation false --create-output-bam-index true --create-output-bam-md5 false --create-output-variant-index true --create-output-variant-md5 false --lenient false --add-output-sam-program-record true --add-output-vcf-command-line true --cloud-prefetch-buffer 40 --cloud-index-prefetch-buffer -1 --disable-bam-index-caching false --sites-only-vcf-output false --help false --version false --showHidden false --verbosity INFO --QUIET false --use-jdk-deflater false --use-jdk-inflater false --gcs-max-retries 20 --gcs-project-for-requester-pays  --disable-tool-default-read-filters false --minimum-mapping-quality 20 --disable-tool-default-annotations false --enable-all-annotations false",Version=4.0.10.0,Date="March 5, 2019 4:08:02 PM PST">`

Some of the resulting vcf records, when run through annovar have their chromosome removed. As an example:
Before annovar
`1       9407759 .       AC      .       86.73   .       AN=2;DP=34;MQ=60.0      GT:AD:DP        0/0:34:34`
After annovar
`9407759 .       AC      .       86.73   .       AN=2;DP=34;MQ=60.00     GT:AD:DP;ANNOVAR_DATE=2018-04-16;cosmic70=.;Func.refGene=intronic;Gene.refGene=SPSB1;GeneDetail.refGene=.;ExonicFunc.refGene=.;AAChange.refGene=.;esp6500siv2_all=.;1000g2015aug_all=.;avsnp147=.;SIFT_score=.;SIFT_converted_rankscore=.;SIFT_pred=.;Polyphen2_HDIV_score=.;Polyphen2_HDIV_rankscore=.;Polyphen2_HDIV_pred=.;Polyphen2_HVAR_score=.;Polyphen2_HVAR_rankscore=.;Polyphen2_HVAR_pred=.;LRT_score=.;LRT_converted_rankscore=.;LRT_pred=.;MutationTaster_score=.;MutationTaster_converted_rankscore=.;MutationTaster_pred=.;MutationAssessor_score=.;MutationAssessor_score_rankscore=.;MutationAssessor_pred=.;FATHMM_score=.;FATHMM_converted_rankscore=.;FATHMM_pred=.;PROVEAN_score=.;PROVEAN_converted_rankscore=.;PROVEAN_pred=.;VEST3_score=.;VEST3_rankscore=.;MetaSVM_score=.;MetaSVM_rankscore=.;MetaSVM_pred=.;MetaLR_score=.;MetaLR_rankscore=.;MetaLR_pred=.;M-CAP_score=.;M-CAP_rankscore=.;M-CAP_pred=.;CADD_raw=.;CADD_raw_rankscore=.;CADD_phred=.;DANN_score=.;DANN_rankscore=.;fathmm-MKL_coding_score=.;fathmm-MKL_coding_rankscore=.;fathmm-MKL_coding_pred=.;Eigen_coding_or_noncoding=.;Eigen-raw=.;Eigen-PC-raw=.;GenoCanyon_score=.;GenoCanyon_score_rankscore=.;integrated_fitCons_score=.;integrated_fitCons_score_rankscore=.;integrated_confidence_value=.;GERP++_RS=.;GERP++_RS_rankscore=.;phyloP100way_vertebrate=.;phyloP100way_vertebrate_rankscore=.;phyloP20way_mammalian=.;phyloP20way_mammalian_rankscore=.;phastCons100way_vertebrate=.;phastCons100way_vertebrate_rankscore=.;phastCons20way_mammalian=.;phastCons20way_mammalian_rankscore=.;SiPhy_29way_logOdds=.;SiPhy_29way_logOdds_rankscore=.;Interpro_domain=.;GTEx_V6_gene=.;GTEx_V6_tissue=.;CLINSIG=.;CLNDBN=.;CLNACC=.;CLNDSDB=.;CLNDSDBID=.;ExAC_ALL=.;ExAC_AFR=.;ExAC_AMR=.;ExAC_EAS=.;ExAC_FIN=.;ExAC_NFE=.;ExAC_OTH=.;ExAC_SAS=.;dbscSNV_ADA_SCORE=.;dbscSNV_RF_SCORE=.;Interpro_domain=.;rmsk=.;Func.ensGene=intronic;Gene.ensGene=ENSG00000171621;GeneDetail.ensGene=.;ExonicFunc.ensGene=.;AAChange.ensGene=.;Func.knownGene=intronic;Gene.knownGene=SPSB1;GeneDetail.knownGene=.;ExonicFunc.knownGene=.;AAChange.knownGene=.;ALLELE_END 0/0:34:34`

The annovar command used to generate this file is as follows
`perl /projects/tvira_prj/tools/annovar/table_annovar.pl error_testing_vcf.vcf /projects/tvira_prj/tools/annovar/humandb/ -buildver hg19 -vcfinput -out /projects/trans_scratch/pedigree_calling/iTARGET_quad/pedcall/K000049/K000049_error_records.vcf_Annovar -remove -protocol cosmic70,refGene,esp6500siv2_all,1000g2015aug_all,avsnp147,dbnsfp33a,clinvar_20170905,exac03,dbscsnv11,dbnsfp31a_interpro,rmsk,ensGene,knownGene -operation f,g,f,f,f,f,f,f,f,f,f,g,g`

I've attached a vcf which when annotated with the above command reproduces the error. Please advise if there is an option I am missing to handle the vcf records formatted by gatk.

[K000049_error_records.txt](https://github.com/WGLab/doc-ANNOVAR/files/2967613/K000049_error_records.txt)

**Comment by kaichop** [comment]
This is a known problem. The reason is that this particular mutation has no meaning based on VCF format specification (there is no alternative allele, and the GT field is listed as 0/0).

1 9407759 . AC . 86.73 . AN=2;DP=34;MQ=60.0 GT:AD:DP 0/0:34:34

I had previously updated convert2nnovar.pl to handle this particular situation (essentially treating the ALT as "0", so at least gene-based and region-based annotation can work) but never updated the package itself. I will include this in the latest package to be released soon.
