### ISSUE TITLE
Error while converting VCF output file from Strelka using convert2annovar.pl program

### ISSUE THREAD

**Issue by flower1996** [WGLab/doc-ANNOVAR#59]
Dear，
 I  try to use the annovar to annotate the vcf output file from  Strelka .
When I am using convert2annovar.pl program to convert the VCF files, get the error below:

```
perl /home/wanglch/biosoftware/annovar/annovar/convert2annovar.pl -format vcf4 sample_strelka.vcf.gz >sample_strelka.aviput
WARNING to old ANNOVAR users: this program no longer does line-to-line conversion for multi-sample VCF files. If you want to include all variants in output, use '-format vcf4old' or use '-format vcf4 -allsample -withfreq' instead.
Error: invalid record in VCF file: the GT specifier is not present in the FORMAT string: <chr1	14653	.	C	T	.	LowEVS	DP=116;MQ=33.58;MQ0=7;NT=ref;QSS=1;QSS_NT=1;ReadPosRankSum=-2.40;SGT=CT->CT;SNVSB=0.00;SOMATIC;SomaticEVS=0.08;TQSS=2;TQSS_NT=2	DP:FDP:SDP:SUBDP:AU:CU:GU:TU	56:0:0:0:0,0:44,48:0,0:12,14	46:0:0:0:0,0:37,38:0,0:9,16>
```
Any Ideas what is going on?
Thanks!

**Comment by kaichop** [comment]
Your file does not contain any genotypes (in the DP:FDP:SDP:SUBDP:AU:CU:GU:TU field). But unless you are an experienced user in annovar, you should only use table_annovar.pl to annotate the file directly, and do not use convert2annovar.

**Comment by felio333** [comment]
I have the same problem using table_annovar.pl
Is there any way to avoid this error? or any way of configure the VCF input file to have this field?
Thanks!

**Comment by kaichop** [comment]
This problem should not happen when using table_annovar.pl

If it happens, you could simply add a GT field, by treating all mutations as 0/1 mutations (heterozygous mutation). Then annotate it.
