### ISSUE TITLE
A question about Annovar 

### ISSUE THREAD

**Issue by WinterLi1993** [WGLab/doc-ANNOVAR#6]
Dear Kai,
     I am using your annovar software ,now I have a question :  
     which dbNSFP version database is used to get SIFT scores, Can you tell me ?
    Thank you very much !

**Comment by kaichop** [comment]
The SIFT score is from dbNSFP database. For example, ljb26 means dbNSFP
v2.6, ljb23 means dbNSFP v2.3. We plan to update to latest dbNSFP soon.

**Comment by WinterLi1993** [comment]
Thank you !,Kai
Expecting your update!

**Comment by kaichop** [comment]
It is available now with keyword dbnsfp30a in ANNOVAR to download. hg18,
hg19 and hg38 are all available.

**Comment by kaichop** [comment]
issue resolved and closed.
