### ISSUE TITLE
Can't download ANNOVAR

### ISSUE THREAD

**Issue by mkmwong** [WGLab/doc-ANNOVAR#60]
Hi, I went to http://annovar.openbioinformatics.org/en/latest/user-guide/download/ and clicked can be download here, and there's no response what so ever. Could you please check what the problem might be? Thanks!

**Comment by kaichop** [comment]
it may be a temporarily internet problem, you can wait one day or two and
see if it comes back online.

**Comment by smlee17** [comment]
Hi, I also tried downloading and its still not working. Is there any possible solution?

**Comment by chenzler** [comment]
I also tried yesterday and today (5/6 and 5/7) and was also unable to download annovar. A couple of times I got a timeout on the download page, a couple of other times both yesterday and today I submitted my request but never got the download email. Is there another way to get access to the download?

**Comment by kaichop** [comment]
You can email me directly. The site is up right now but may take some time
for DNS to propagate, and some DBs are not available to download right now.
