### ISSUE TITLE
Missing Polyphen in hg19/hg38? 

### ISSUE THREAD

**Issue by student-t** [WGLab/doc-ANNOVAR#63]
The Polyphen scoring seem to be missing in both hg19/hg38. For example:

    wget http://www.openbioinformatics.org/annovar/download/hg19_dbnsfp35c.txt.gz
    gunzip hg19_dbnsfp35c.txt.gz
    grep Polyphen hg19_dbnsfp35c.txt | wc

0 line counted.

On http://annovar.openbioinformatics.org/en/latest/misc/accessory, it says there should be a "Polyphen" column, but there shouldn't.

Should we add Polyphen back?

**Comment by kaichop** [comment]
You can check the first row of the file which should list all columns.
polyphen should be there but the name may not be "Polyphen" exactly.
