### ISSUE TITLE
gnomad_exome and gnomad_genome not updated (still 2017)?

### ISSUE THREAD

**Issue by student-t** [WGLab/doc-ANNOVAR#66]
According to the website, gnomAD is now up to version 2.1.1, from a recent release in 2019.

However, ```./annotate_variation.pl -webfrom annovar -downdb avdblist -buildver hg38``` is still giving both `gnomad_genome` and `gnomad_exome` from 2017.

How should I proceed?

**Comment by kaichop** [comment]
use gnomad211_genome and gnomad211_exome

**Comment by student-t** [comment]
It worked. Thanks!
