### ISSUE TITLE
Internal sever error when trying to downlaod prepare_annovar_user.pl

### ISSUE THREAD

**Issue by Hansol-Park** [WGLab/doc-ANNOVAR#68]
Hi, I'm trying to use your Annovar software. 

To make an annovar database for latest COSMIC data, I tried to download "prepare_annovar_user.pl" at

http://www.openbioinformatics.org/annovar/download/prepare_annovar_user.pl

But, it gave the following error message:

-----------------------------------------------------------------------------------------------------------
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@openbioinformatics.genotypic.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.
----------------------------------------------------------------------------------------------------------

I sent an email to the email address above, but the email sent was failed. So, I ask the question here.  

Regards,

Hansol

**Comment by kaichop** [comment]
You can change the pl to txt and download again.
