### ISSUE TITLE
annovar frameshift deletion issue

### ISSUE THREAD

**Issue by fengdong110** [WGLab/doc-ANNOVAR#69]
Dear friends:

When I annotate my vcf,  I find the annovar annotate frameshift site is different from other people's results. 
1、 The following graph is my annotate result:
![image](https://user-images.githubusercontent.com/19946295/59413059-643f1000-8df1-11e9-8b8a-beea85126a7c.png)
2、The following graph is other people result，I don't know what software he used to annotate
![image](https://user-images.githubusercontent.com/19946295/59413169-9badbc80-8df1-11e9-9dcf-0b952d970dfa.png)

Question: the same position，the same ref and the same alt. but the c.  and p. is different。 I don't know why。What causes this difference？？

**Comment by kaichop** [comment]
looks like you did not use -polish. Read FAQ #1 and provide details.

**Comment by fengdong110** [comment]
thank you very much

**Comment by fengdong110** [comment]
@kaichop     

I know the reason of different.   Because the mutation occurs at homopolymer region . annovar thought the del occur in front. but other people's results thought in end.
![image](https://user-images.githubusercontent.com/19946295/59477166-93539100-8e86-11e9-892d-9974ad828bd7.png)

And i use "-polish" parameter  run it again. I found the p. is correct with other people's result. but the c. still think the del in front.
![image](https://user-images.githubusercontent.com/19946295/59477505-ff82c480-8e87-11e9-94e6-aeed23cca0f7.png)
![image](https://user-images.githubusercontent.com/19946295/59477526-175a4880-8e88-11e9-938c-0a3030c623a2.png)

I want to know. if the annovar have parameter think  homopolymer del in the end???  let c. correct with other people's result.

**Comment by kaichop** [comment]
The input is provided by you, and ANNOVAR annotates the exact mutation that
you provide.
If you have VCF files, you need to do a left normalization, then annotate
the new mutation. See
http://annovar.openbioinformatics.org/en/latest/articles/VCF/
