### ISSUE TITLE
How to build database for virus in annovar 

### ISSUE THREAD

**Issue by Ramanandan** [WGLab/doc-ANNOVAR#7]
Dear Wang,

I am working on a virus. Can you please help me to build the database for virus in order to perform annotation of variants.

**Comment by kaichop** [comment]
Please read
http://annovar.openbioinformatics.org/en/latest/user-guide/gene/#what-about-gff3-file-for-new-species

We recently published a protocol that you may find useful as well, as it
gives concrete examples:
http://www.nature.com/nprot/journal/v10/n10/abs/nprot.2015.105.html

**Comment by Ramanandan** [comment]
Dear Kai Wang, 

Thanks for answering my query promptly. I am currently working to annotate the variants from influenza virus. I have 8 segments for this virus strain.
