### ISSUE TITLE
Getting zygosity (HOM or HET) in a column in txt output

### ISSUE THREAD

**Issue by hamidqaedi** [WGLab/doc-ANNOVAR#72]
Hi Developers,
Is there any method (code) to get variant zygosity into a column? 
I tried to find the solution with` -withzyg` option, but still lacking zygosity column in the final output.
Any advice is greatly appreciated. 
Hamid

**Comment by hamidqaedi** [comment]
I figured it out using python and R. No I have such column in the annotation file. 
I suppose it should be incorporated into annotation file by default, as you may find in the output of other software like SnpEff.
Hamid

**Comment by kaichop** [comment]
I missed this issue and did not respond earlier. -withzyg should print out
the hom and het status. Then you annotate the file, and the additional
column will be included in the final output (regardless of format), when
-otherinfo argument is included in table_annovar.
