### ISSUE TITLE
Is the same default precedence used for refgene and ensgene annotation? Can one annoyed Sequence Ontology Terms?

### ISSUE THREAD

**Issue by roselucia** [WGLab/doc-ANNOVAR#74]
Hi guys,

does the default precedence, as shown in Output file 1 (refSeq gene), as well as the definitions of the ExonicFunc Annotations and their precedence, as shown in Output file 2 (refSeq gene), are equal for the Ensemble Annotation?
Is there a chance to annotate the variants with Sequence Ontology terms?

Thanks!
Rose

**Comment by kaichop** [comment]
The precedence is equal, whether refseq gene, or ensemble gene, is used as
the gene definition.
The variants cannot be annotated by sequence ontology terms, but there is a
table that translate some of the annotations into sequence ontology terms.
SO is generally formed as a tree like structure, yet annotation from
annovar are categorial (mutually exclusive, without parent terms and child
terms).

**Comment by roselucia** [comment]
Thanks a lot for you response!
May I ask you ohne other question:
In the technical comment in the section Polyphen 2 it si described, that if more than one score exists (due to multiple isoforms) only the largest score (most deleterious) is used in the annotation. How does Annovar deal with multiple scores when annotating the scores of the dataset dbnsfp30a, such as SIFT, MutationTaster, etc.? Is always the most deleterious one/the one with the highes impact used?

Thanks!
All the best

**Comment by kaichop** [comment]
For dbNSFP, starting from 2017Feb21: We now added the rankscore for each scoring system, and for variants with multiple prediction scores, only the most deleterious (rather than highest) scores are kept.
