### ISSUE TITLE
Argument "G" isn't numeric in numeric eq....

### ISSUE THREAD

**Issue by hamidqaedi** [WGLab/doc-ANNOVAR#75]
Hi Developers,
Just before finishing the command "table_annovar.pl" ,  lines are  printing on the screen. 

```
`Argument "G" isn't numeric in numeric eq (==) at ./annotate_variation.pl line 2583, <DB> line 768929.
Argument "C" isn't numeric in numeric eq (==) at ./annotate_variation.pl line 2583, <DB> line 768930.
Argument "A" isn't numeric in numeric eq (==) at ./annotate_variation.pl line 2583, <DB> line 768931.
Argument "G" isn't numeric in numeric eq (==) at ./annotate_variation.pl line 2583, <DB> line 768932.
Argument "A" isn't numeric in numeric eq (==) at ./annotate_variation.pl line 2583, <DB> line 768933.
Argument "G" isn't numeric in numeric eq (==) at ./annotate_variation.pl line 2583, <DB> line 768934.
Argument "G" isn't numeric in numeric eq (==) at ./annotate_variation.pl line 2583, <DB> line 768935.
Argument "G" isn't numeric in numeric eq (==) at ./annotate_variation.pl line 2583, <DB> line 768936.
Argument "G" isn't numeric in numeric eq (==) at ./annotate_variation.pl line 2583, <DB> line 768937.
Argument "C" isn't numeric in numeric eq (==) at ./annotate_variation.pl line 2583, <DB> line 768938.
Argument "C" isn't numeric in numeric eq (==) at ./annotate_variation.pl line 2583, <DB> line 768939.
Argument "T" isn't numeric in numeric eq (==) at ./annotate_variation.pl line 2583, <DB> line 768940.

Done
`
```
This is while all the process for me take about 20 minutes to complete just before the step of printing the lines. The printing takes about 1 hour. Just after this process is done, I receive comments show the annotation job is done.
 
Any suggestion?

**Comment by kaichop** [comment]
Read FAQ #1 and #4.

**Comment by hamidqaedi** [comment]
Dear Dr Kai Wang,
Thanks for your answer.
But still I have no idea what is happening. I read both FAQs #1 and #4 . 
Actually FAQ #1 is about using -vcfinput and -csvout in the command. This is not my case. 
I am using annovar as a part of my pipeline and the code chunk relevant to annovar in my script is as follows:
`rule avinput:
    input:  "VCF_final/{sample}_filtered_final.vcf",
    output: "ANNO/avi.{sample}.avinput",
    params:
           toanno = CTA,
    priority:14,
    shell: """
         mkdir -p ANNO
         perl {params.toanno} -format vcf4 {input} -outfile ./ANNO/avi -allsample -include -withzyg > {output}
        """
rule annovar:
    input:  rules.avinput.output,
    output: "ANNO/{sample}.hg19_multianno.txt",
    params:
          table2annovar = TTA,
          humandb = HUMANDB,
    priority:15,
    shell: """
          perl {params.table2annovar} {input} {params.humandb} \
         -buildver hg19 -out /ANNO/sample\
         -remove \
         -protocol refGene,avsnp150,iranome,abraom,dbnsfp33a,ALL.sites.2015_08,clinvar_20190305,gnomad_exome,gme,kaviar_20150923 \
         -operation g,f,f,f,f,f,f,f,f,f \
         -nastring . -polish --thread 64 \
`
About FAQ #4 I am not sure what to do. Do I need to change default of an annovar config file ?
Appreciate your time and reply.
Hamid

**Comment by kaichop** [comment]
FAQ #1 asked you to send the actual command so that I can advise what is
wrong.

FAQ #4 gives the keyword to use. In this case, ALL.sites.2015_08 is not the
correct keyword to use, and you have to use 1000g2015aug_all instead due to
historical reasons. I may change the program to handle the keyword issue
because it is a re-occurring issue for many people.

**Comment by kaichop** [comment]
This is a re-occurring issue and I have made changes to code so that ALL.sites.2015_08 can be a valid keyword in future versions of ANNOVAR. It will be released soon. I will close this issue.
