### ISSUE TITLE
Convert2Annovar produces empty file?

### ISSUE THREAD

**Issue by vctrm67** [WGLab/doc-ANNOVAR#76]
Hi, 

I have some vcf files for WES data that I wanted to run through Convert2Annovar, because I would like a csv output. However, I am getting a 0B file for this command: 

`/home/mk446/bin/annovar/convert2annovar.pl -format 'vcf4' 'combined.vcf' -outfile 'combined.avinput' -allsample`

I'm not sure why. When I run Annovar, it doesnt seem like there's any error too. Does anyone know what is going on?

**Comment by kaichop** [comment]
Do not use convert2annovar. If you have a VCF file, just use table_annovar
to annotate it. It can generate tab delimited or csv output.

**Comment by vctrm67** [comment]
How do I specify a csv output with a vcf file? If I use -vcfinput and -csvoutput it gives me an error?

**Comment by kaichop** [comment]
There are two ways: (1) you can just generate a text output, and convert it to CSV file using a script, or using any software such as Excel (2) when you run table_annovar.pl you will see the correct command for running convert2annovar, and you will have the avinput file as a temporary file, so you can just annotate this intermediate file with -csvout and table_annovar.
