### ISSUE TITLE
Software downloading error

### ISSUE THREAD

**Issue by xiucz** [WGLab/doc-ANNOVAR#78]
hi,

I tried to register to  download the lastest version(2019Oct24), but it returned an error "Please enter your full institution name with more than 10 characters.". As  institutional email address ended up with "edu.cn" and the characters before "@" more than 10.

Can you help to solve the bug? Or did I miss something?

**Comment by kaichop** [comment]
edu.cn should work. You need to enter your full institution name in the form though. For example, you cannot use "CAS" but need to use "Chinese Academy of Science" as the full name of the institution.
