### ISSUE TITLE
gff3toGenePred command not found

### ISSUE THREAD

**Issue by Ramanandan** [WGLab/doc-ANNOVAR#8]
Dear Kai Wang,

Follow up to this How to build database for virus in annovar.

I created gff3 file from each gene's genbank file of a virus. As you mentioned, I referred following section in website and the recent nature protocol paper. 

What about GFF3 file for new species?
Then go to http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/, download the gff3ToGenePred tool, and convert the GFF3 file to a format that ANNOVAR can read. Everything else is the same as above.

As per the link, I downloaded gff3toGenePred program in to my local machine. 
gff3ToGenePred - convert a GFF3 file to a genePred file
usage:
   gff3ToGenePred inGff3 outGp

I received following message when executing this command 

$gff3ToGenePred gff_files/input.gff outputGP
gff3ToGenePred: command not found

**Comment by younghuman** [comment]
HI, Ramanandan 

First, you have to make executable permission to it.

chmod 775 gff3ToGenePred

Next, please run as (suppose gff3ToGenePred is in your current dir)
./gff3ToGenePred

**Comment by Ramanandan** [comment]
Thanks for help. Yeah even I did they same thing. But I executed the command without gff3ToGenePred without ./

Now I receive the following error.  
"../gff_files/HAgene.gff:13: CDS feature must have phase
GFF3: 1 parser errors"

I am currently working to annotate the variants from influenza virus. I have 8 segments for this virus strain. There is no genome sequence with all genes as one genbank file. So I have combined all the 8 gene sequences in fasta format.

Inorder to create GFF3, I used each genes genbank file to create a GFF3 file using genbanktoGFF3.pl program.

I might be wrong in doing this process. can you correct me please

**Comment by younghuman** [comment]
I have no idea what's wrong in your process. From my personal experience, GTF is better and also recommended in the Nature Protocols paper we wrote.

**Comment by Ramanandan** [comment]
I have already used annovar for human genome. But this time, I am working with influenza virus. I am struggling in generating gff3 or gtf file for the virus. I am not working on the genome file, instead I am working only with the 8 gene files. I am confused how to generate gff3 or gtf from gene file.

**Comment by younghuman** [comment]
You have to get the position relative to the reference genome to get information for GTF file. 
Please refer to http://www.ensembl.org/info/website/upload/gff.html.
It seems to me the GenBank format does not have that information.
To have that, you have to make sure the species you study 1) has a reference genome 2) has a gene definition or at least prediction.
If so, you need to retrieve the start and end position of each feature corresponding to each of your 8 genes, including Gene, Transcript, CDS, so on. 

A sample GTF file can be found ftp://ftp.ensemblgenomes.org/pub/release-29/plants/gtf/aegilops_tauschii
