### ISSUE TITLE
Download and unpack Annovar tar xvfz annovar.latest.tar.gz

### ISSUE THREAD

**Issue by roselucia** [WGLab/doc-ANNOVAR#81]
Hi Kai,
I have a rather basic question:
I downloaded the new Annovar version via Safari, as downloading it with the terminal did not work. I used various commands to download the file URL, which was sent to me after registration, such as:
curl - o annovar.latest.tar.gz "URL"
However the downloaded file was empty (0 Byte). 
I downloaded it via the Safari Browser now instead and unpacked the downloaded file annovar.tar in the terminal with the command tar xvfz annovar.tar
I used my MacBook Pro (13'', Anfang 2011),macOS High Sierra 10.13.6 and the browser Safari version 13.01.

Is it ok to use the download from Safari?

Thanks a lot!
Rose

The following content was seen in the terminal when unpacking the Safari download.
Last login: Wed Nov  6 20:49:09 on ttys000
Rose-Frohlichs-MacBook-Pro:~ rosefroehlich$ cd /Users/rosefroehlich/Desktop/Annovar_Safari_Download 
Rose-Frohlichs-MacBook-Pro:Annovar_Safari_Download rosefroehlich$ tar xvfz annovar.tar
x annovar/
x annovar/example/
x annovar/example/ex1.avinput
x annovar/example/example.simple_region
x annovar/example/example.tab_region
x annovar/example/ex2.vcf
x annovar/example/grantham.matrix
x annovar/example/snplist.txt
x annovar/example/README
x annovar/example/gene_xref.txt
x annovar/example/gene_fullxref.txt
x annovar/humandb/
x annovar/humandb/hg19_refGene.txt
x annovar/humandb/hg19_refGeneMrna.fa
x annovar/humandb/hg19_refGeneVersion.txt
x annovar/humandb/hg19_refGeneWithVer.txt
x annovar/humandb/hg19_refGeneWithVerMrna.fa
x annovar/humandb/hg19_example_db_generic.txt
x annovar/humandb/hg19_example_db_gff3.txt
x annovar/humandb/GRCh37_MT_ensGene.txt
x annovar/humandb/GRCh37_MT_ensGeneMrna.fa
x annovar/humandb/hg19_MT_ensGene.txt
x annovar/humandb/hg19_MT_ensGeneMrna.fa
x annovar/humandb/genometrax-sample-files-gff/
x annovar/humandb/genometrax-sample-files-gff/list
x annovar/humandb/genometrax-sample-files-gff/sample_chip_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_common_snp_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_cosmic_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_cpg_islands_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_dbnsfp_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_disease_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_dnase_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_drug_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_evs_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_gwas_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_hgmd_common_snp_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_hgmd_disease_genes_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_hgmd_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_hgmdimputed_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_miRNA_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_microsatellites_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_omim_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_pathway_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_pgx_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_ptms_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_snps_dbsnp_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_snps_ensembl_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_transfac_sites_featuretype_hg19.gff
x annovar/humandb/genometrax-sample-files-gff/sample_tss_featuretype_hg19.gff
x annovar/annotate_variation.pl
x annovar/table_annovar.pl
x annovar/convert2annovar.pl
x annovar/retrieve_seq_from_fasta.pl
x annovar/coding_change.pl
x annovar/variants_reduction.pl

**Comment by kaichop** [comment]
This looks okay to me. You can also use "wget" to download a file from a URL.
