### ISSUE TITLE
Cosmicv90 Warning prepare_annovar_user.pl

### ISSUE THREAD

**Issue by roselucia** [WGLab/doc-ANNOVAR#82]
Hi Kai,
In order to be able to annotate Cosmic_v90, I used the prepare_annovar_user.pl downloaded from http://www.openbioinformatics.org/annovar/download/prepare_annovar_user.pl for cosmic v90? 
I received this warning:"WARNING: 11821 COSMIC ID from MutantExport file cannot be found in VCF file (this may be normal if the VCF file only contains coding or noncoding variants".
Logs:
$ cd /Users/rosefroehlich/Desktop/Cosmic_v90 
$ perl prepare_annovar_user.pl -dbtype cosmic CosmicNCV.tsv -vcf CosmicNonCodingVariants.vcf > hg19_cosmic90_noncoding.txt
NOTICE: Finished reading 14238468 mutation ID from the VCF file CosmicNonCodingVariants.vcf
NOTICE: Finished reading 14238418 COSMIC records in DB file CosmicNCV.tsv
WARNING: 11821 COSMIC ID from MutantExport file cannot be found in VCF file (this may be normal if the VCF file only contains coding or noncoding variants

I received the same warning for the coding variants:  1 COSMIC ID from MutantExport file cannot be found in VCF file (this may be normal if the VCF file only contains coding or noncoding variants

Logs:
$ cd /Users/rosefroehlich/Desktop/Cosmic_v90 
$ perl prepare_annovar_user.pl -dbtype cosmic CosmicMutantExport.tsv -vcf CosmicCodingMuts.vcf > hg19_cosmic90_coding.txt
NOTICE: Finished reading 10068058 mutation ID from the VCF file CosmicCodingMuts.vcf
NOTICE: Finished reading 10064082 COSMIC records in DB file CosmicMutantExport.tsv

Did my commands work correctly?

Thanks a lot!
Rose

**Comment by kaichop** [comment]
looks okay to me. You can count the # variants in the final output file
just to make sure.

**Comment by roselucia** [comment]
Thanks Kai! Does that look right?
$ wc hg19_cosmic90_noncoding.txt hg19_cosmic90_coding.txt 
 14238418 85430508 940290628 hg19_cosmic90_noncoding.txt
 10064082 60384492 665231304 hg19_cosmic90_coding.txt
 24302500 145815000 1605521932 total

All the best
