### ISSUE TITLE
-neargene parameter

### ISSUE THREAD

**Issue by arumds** [WGLab/doc-ANNOVAR#94]
Dear Kai,

Could you let me know what is the unit for the number given to `‘-neargene’` parameter? is it bp or kb?

I have been using `‘-neargene 2’` parameter to define variants which are 2-kb as upstream/downstream. However, all the upstream/downstream variants have dist=1.  Does it mean that the argument is not parsed correctly or could it be that all the input variants are within 1-kb?

In addition how can we set the threshold for `'-neargene’`  as 200bp?

**Comment by kaichop** [comment]
The unit is base pair. So 2kb should be '-neargene 2000', rather than 'neargene 2'.
